Enables Jenkins to trigger jobs on repo update events by AWS CodeCommit
through SQS and SNS.

[[AWSCodeCommitTriggerPlugin-Introduction]]
=== Introduction

A Jenkins plugin that triggers jobs on repo update events by AWS
CodeCommit, through the AWS Simple Queue Service (SQS) and Simple
Notification Service (SNS).

 

The advantage over the https://github.com/jenkinsci/aws-sqs-plugin[AWS
SQS Plugin] is that this plugin allows:

* subscribing to multiple branches using the same SQS queue
* subscribing to multiple repos using the same SQS queue

There are several (advantageous) implications:

* you no longer need to create a SQS queue per CodeCommit repo
* an update to the `+dev+` branch will no longer trigger all jobs that
subscribe to that CodeCommit repo.

Quick Setup With Terraform

Use
the https://github.com/riboseinc/tf-codecommit-sqs[tf-codecommit-sqs] module
to create your CodeCommit repos created with provided linkage with
SQS/SNS.

[[AWSCodeCommitTriggerPlugin-Authors]]
=== Authors

AWS CodeCommit Trigger Plugin is provided
by https://www.ribose.com/[Ribose Inc.] (GitHub
page: https://github.com/riboseinc[Ribose Inc.])

The original https://github.com/jenkinsci/aws-sqs-plugin[AWS SQS
Plugin] was written (and still maintained)
by https://github.com/mpfeiffermway[Markus Pfeiffer] of M-Way Solutions
GmbH.

 

More Details

See this link for
details: https://github.com/riboseinc/aws-codecommit-trigger-plugin
