[.conf-macro .output-inline]#Simpler version of
https://wiki.jenkins-ci.org/display/JENKINS/Promoted+Builds+Plugin[Promoted
Builds Plugin], with only manual promotion of builds.#

This plugin adds a `+Promoted Builds+` section in the main Jenkins
configuration page. Here you can configure the names of your promotion
levels and the icons to use in the Build History. All builds run after
the plugin is installed will show the promotion level on the build
status page, and users with "Update Run" permission will be able to
promote the build.

Unlike the
https://wiki.jenkins-ci.org/display/JENKINS/Promoted+Builds+Plugin[Promoted
Builds Plugin], this plugin defines metadata only; there is no action
associated with the promotion. It just shows the promotion level on the
build page and a badge icon in the Build History on the project page.
You may use this metadata however you like, such as using the Remote API
to find artifacts of a particular promotion level. The
https://wiki.jenkins-ci.org/display/JENKINS/Copy+Artifact+Plugin[Copy
Artifact Plugin] can also copy artifacts of a selected promotion level
from other jobs.

Click the help icon for Promoted Builds in the main configuration page
for information on how to use the Remote API to query for promoted
builds, or how to promote builds that were run before installing the
plugin.

'''''

[[PromotedBuildsSimplePlugin-ChangeLog]]
== Change Log

[[PromotedBuildsSimplePlugin-Version1.9(Mar29,2011)]]
=== Version 1.9 (Mar 29, 2011)

* Japanese translation updates.

[[PromotedBuildsSimplePlugin-Version1.8(Feb25,2011)]]
=== Version 1.8 (Feb 25, 2011)

* Rerelease 1.7 to properly set required Jenkins version.

[[PromotedBuildsSimplePlugin-Version1.7(Feb13,2011)]]
=== Version 1.7 (Feb 13, 2011)

* Add configuration option for whether promotion to each level
automatically marks the build as "keep forever".
(https://issues.jenkins-ci.org/browse/JENKINS-7284[JENKINS-7284])
* When using
https://wiki.jenkins-ci.org/display/JENKINS/Copy+Artifact+Plugin[Copy
Artifact Plugin], check promotion level of parent build for maven or
matrix project when copying artifacts from a particular maven module or
matrix configuration.
(https://issues.jenkins-ci.org/browse/JENKINS-7900[JENKINS-7900])
* Add ability to upload image files into JENKINS_HOME/userContent
directory from global config page.

[[PromotedBuildsSimplePlugin-Version1.6(May12,2010)]]
=== Version 1.6 (May 12, 2010)

* Avoid many exceptions in log when Copy Artifact plugin is not also
installed.

[[PromotedBuildsSimplePlugin-Version1.5(May8,2010)]]
=== Version 1.5 (May 8, 2010)

* Fix setting in Copy Artifact build step so it shows the saved value
for promotion level when returning to job config page.
* Add support in Copy Artifact build step to get the promotion level
from a build parameter or environment variable.

[[PromotedBuildsSimplePlugin-Version1.4(Apr17,2010)]]
=== Version 1.4 (Apr 17, 2010)

* Add support for selecting promoted builds with the
https://wiki.jenkins-ci.org/display/JENKINS/Copy+Artifact+Plugin[Copy
Artifact Plugin].

[[PromotedBuildsSimplePlugin-Version1.3(Apr13,2010)]]
=== Version 1.3 (Apr 13, 2010)

* Add Japanese localization
(https://issues.jenkins-ci.org/browse/JENKINS-6226[JENKINS-6226]).

[[PromotedBuildsSimplePlugin-Version1.2(Feb10,2010)]]
=== Version 1.2 (Feb 10, 2010)

* Update code for more recent Hudson.

[[PromotedBuildsSimplePlugin-Version1.1(Jul14,2009)]]
=== Version 1.1 (Jul 14, 2009)

* Set visibility of exported data to enable xpath query with depth=1
instead of depth=2 (which exposes more data and slows down the query).

[[PromotedBuildsSimplePlugin-Version1.0(Jun23,2009)]]
=== Version 1.0 (Jun 23, 2009)

* Initial release.
