[.conf-macro .output-inline]#This plugin lets you generate
http://jgiven.org/[JGiven] reports as a post-build action.#

[[JGivenPlugin-JobDSL]]
== Job DSL

The current supported dsl is as follows:

[source,syntaxhighlighter-pre]
----
freeStyleJob('test-job') {
  publishers {
    jgivenReports {
      excludeEmptyScenarios() // Since 0.10
      html {
        customCss 'some.css'
        customJs 'some.js'
        title 'My Custom Title'
      }
      results '**/*.json'
    }
  }
}
----

[[JGivenPlugin-Changelog]]
== Changelog

[[JGivenPlugin-0.10.0(25.12.2015)]]
=== 0.10.0 (25.12.2015)

* image:docs/images/warning.svg[(warning)]
Custom Files (js/css) are now taken from the workspace of the build and
the path is interpreted relative to the workspace of the build
(https://issues.jenkins-ci.org/browse/JENKINS-30981[JENKINS-30981])
* Updated JGiven to 0.10.1 and added support to configure to exclude
empty scenarios
(https://issues.jenkins-ci.org/browse/JENKINS-31337[JENKINS-31337])

[[JGivenPlugin-0.9.1(14.10.2015)]]
=== 0.9.1 (14.10.2015)

* Updated JGiven to 0.9.1
* First two digits of the version now indicate the version of JGiven
used

[[JGivenPlugin-0.9.0(11.10.2015)]]
=== 0.9.0 (11.10.2015)

* Release failed - only SNAPSHOT was published

[[JGivenPlugin-0.2(25.9.2015)]]
=== 0.2 (25.9.2015)

* Added support for the
https://wiki.jenkins-ci.org/display/JENKINS/Job+DSL+Plugin[Job DSL
Plugin].
* Upgraded JGiven to 0.8.2
* Only one Html Report (= previously called Html5 report) is supported

[[JGivenPlugin-0.1.1(21.02.2015)]]
=== 0.1.1 (21.02.2015)

* Renamed Plugin from jgiven-plugin to jgiven - existing installations
need to install the new plugin and deinstall the old one.

[[JGivenPlugin-0.1(18.02.2015)]]
=== 0.1 (18.02.2015)

* Initial Release
