[[GitHubOAuthPlugin-AboutGitHubAuthenticationPlugin]]
== About GitHub Authentication Plugin

The GitHub Authentication Plugin provides a means of using GitHub for
authentication and authorization to secure Jenkins. GitHub Enterprise is
also supported.[.conf-macro .output-inline]##

[cols="",options="header",]
|===
|Plugin Information
|View GitHub Authentication https://plugins.jenkins.io/github-oauth[on
the plugin site] for more information.
|===

[.aui-icon .aui-icon-small .aui-iconfont-info .confluence-information-macro-icon]##

Older versions of this plugin may not be safe to use. Please review the
following warnings before using an older version:

* https://jenkins.io/security/advisory/2019-04-30/#SECURITY-443[CSRF
vulnerability in OAuth callback]
* https://jenkins.io/security/advisory/2019-01-28/#SECURITY-602[Client
secret displayed in plain text]
* https://jenkins.io/security/advisory/2019-01-28/#SECURITY-797[Session
fixation vulnerability]

*On this page:*

[[GitHubOAuthPlugin-Setup]]
== Setup

Before configuring the plugin you must create a GitHub application
registration.

. Visit https://github.com/settings/applications/new to create a GitHub
application registration.
. The values for application name, homepage URL, or application
description don't matter. They can be customized however desired.
. However, the authorization callback URL takes a specific value. It
must be `+https://jenkins.example.com/securityRealm/finishLogin+` where
jenkins.example.com is the location of the Jenkins server.
+
[.aui-icon .aui-icon-small .aui-iconfont-warning .confluence-information-macro-icon]#
#

The important part of the callback URL is `+/securityRealm/finishLogin+`
. Finish by clicking _Register application_.

[.aui-icon .aui-icon-small .aui-iconfont-info .confluence-information-macro-icon]#
#

The _Client ID_ and the _Client Secret_ will be used to configure the
Jenkins Security Realm. Keep the page open to the application
registration so this information can be copied to your Jenkins
configuration.

[[GitHubOAuthPlugin-SecurityRealminGlobalSecurity]]
=== Security Realm in Global Security

The security realm in Jenkins controls authentication (i.e. you are who
you say you are). The GitHub Authentication Plugin provides a security
realm to authenticate Jenkins users via GitHub OAuth.

. In the Global Security configuration choose the Security Realm to be
*GitHub Authentication Plugin*.
. The settings to configure are: GitHub Web URI, GitHub API URI, Client
ID, Client Secret, and OAuth Scope(s).
. If you're using GitHub Enterprise then the API URI is
https://ghe.example.com/api/v3.
+
[.aui-icon .aui-icon-small .aui-iconfont-warning .confluence-information-macro-icon]#
#

The GitHub Enterprise API URI ends with `+/api/v3+`.
. The recommended minimum
https://developer.github.com/v3/oauth/#scopes[GitHub OAuth scopes] are
`+read:org,user:email+`.
+
[.aui-icon .aui-icon-small .aui-iconfont-approve .confluence-information-macro-icon]#
#

The recommended scopes are designed for using both authentication and
authorization functions in the plugin. If only authentication is being
used then the scope can be further limited to `+(no scope)+` or
`+user:email+`.

[.aui-icon .aui-icon-small .aui-iconfont-info .confluence-information-macro-icon]#
#

In the plugin configuration pages each field has a little
image:docs/images/help_16.svg[(question)]
next to it. Click on it for help about the setting.

[[GitHubOAuthPlugin-AuthorizationinGlobalSecurity.]]
=== Authorization in Global Security.

The authorization configuration in Jenkins controls what your users can
do (i.e. read jobs, execute builds, administer permissions, etc.). The
GitHub OAuth Plugin supports multiple ways of configuring authorization.

[.aui-icon .aui-icon-small .aui-iconfont-warning .confluence-information-macro-icon]#
#

It is highly recommended that you configure the security realm and log
in via GitHub OAuth before configuring authorization. This way Jenkins
can look up and verify users and groups if configuring matrix-based
authorization.

[[GitHubOAuthPlugin-GithubCommitterAuthorizationStrategy]]
==== Github Committer Authorization Strategy

Control user authorization using the *Github Committer Authorization
Strategy*. This is the simplest authorization strategy to get up and
running. It handles authorization based on the git URL of a job and the
type of access a user has to that project (i.e. Admin, Read/Write,
Read-Only).

[.aui-icon .aui-icon-small .aui-iconfont-info .confluence-information-macro-icon]#
#

There is a way to authorize the use of the `+/github-webhook+` callback
url to receive post commit hooks from GitHub. This authorization
strategy has a checkbox that can allow GitHub POST data to be received.
You will still need to run the
https://wiki.jenkins-ci.org/display/JENKINS/GitHub+Plugin[GitHub Plugin]
to have the message trigger the build.

[[GitHubOAuthPlugin-Logged-inuserscandoanything]]
==== Logged-in users can do anything

There are a few ways to configure the plugin so that everyone on your
team has `+Overall/Administer+` access.

. Choose *Logged-in users can do anything* authorization strategy.
. Choose one of the matrix-based authorization strategies. Set
`+authenticated+` users to `+Overall/Administer+` permissions. Set
`+anonymous+` users to have `+Overall/Read+` permissions and perhaps the
`+ViewStatus+` permission.

[[GitHubOAuthPlugin-Matrix-basedAuthorizationstrategy]]
==== Matrix-based Authorization strategy

Control user authorization using *Matrix-based security* or
*Project-based Matrix Authorization Strategy*. Project-based Matrix
Authorization Strategy allows one to configure authorization globally
per project and, when using Project-based Matrix Authorization Strategy
with the CloudBees folder plugin, per folder.

There are a few built-in authorizations to consider.

* `+anonymous+` - is anyone who has not logged in. Recommended
permissions are just `+Job/Discover+` and `+Job/ViewStatus+`.
* `+authenticated+` - is anyone who has logged in. You can configure
permissions for anybody who has logged into Jenkins. Recommended
permissions are `+Overall/Read+` and `+View/Read+`.
+
[.aui-icon .aui-icon-small .aui-iconfont-warning .confluence-information-macro-icon]#
#

`+anonymous+` and `+authenticated+` usernames are case sensitive and
must be lower case. This is a consideration when configuring
authorizations via Groovy. Keep in mind that `+anonymous+` shows up as
_Anonymous_ in the Jenkins UI.

You can configure authorization based on GitHub users, organizations, or
teams.

* `+username+` - give permissions to a specific GitHub username.
* `+organization+` - give permissions to every user that belongs to a
specific GitHub organization.
* `+organization*team+` - give permissions to a specific GitHub team of
a GitHub organization. Notice that organization and team are separated
by an asterisk (`+*+`).

[[GitHubOAuthPlugin-Otherusage]]
== Other usage

[[GitHubOAuthPlugin-CallingJenkinsAPIusingGitHubPersonalAccessTokens]]
=== Calling Jenkins API using GitHub Personal Access Tokens

You can make Jenkins API calls by using a GitHub personal access token.
One can still call the Jenkins API by using Jenkins tokens or use the
Jenkins CLI with an SSH key for authentication. However, the GitHub
OAuth plugin provides another way to call the Jenkins API by allowing
the use of a GitHub Personal Access Token.

. Generate a https://github.com/settings/tokens[GitHub _Personal Access
Token_] and give it only `+read:org+` scope.
. Use a username and GitHub personal access token to authenticate with
the Jenkins API.

Here's an example using curl to start a build using parameters (username
`+samrocketman+` and password using the personal access token).

[source,syntaxhighlighter-pre]
----
curl -X POST https://jenkins.example.com/job/_jervis_generator/build --user "samrocketman:myGitHubPersonalAccessToken" --data-urlencode json='{"parameter": [{"name":"project", "value":"samrocketman/jervis"}]}'
----

[[GitHubOAuthPlugin-Automaticallyconfiguresecurityrealmviascriptconsole]]
=== Automatically configure security realm via script console

Configuration management could be used to configure the security realm
via the
https://wiki.jenkins-ci.org/display/JENKINS/Jenkins+Script+Console[Jenkins
Script Console]. Here's a sample configuring plugin version 0.22.

[source,syntaxhighlighter-pre]
----
import hudson.security.SecurityRealm
import org.jenkinsci.plugins.GithubSecurityRealm
String githubWebUri = 'https://github.com'
String githubApiUri = 'https://api.github.com'
String clientID = 'someid'
String clientSecret = 'somesecret'
String oauthScopes = 'read:org'
SecurityRealm github_realm = new GithubSecurityRealm(githubWebUri, githubApiUri, clientID, clientSecret, oauthScopes)
//check for equality, no need to modify the runtime if no settings changed
if(!github_realm.equals(Jenkins.instance.getSecurityRealm())) {
    Jenkins.instance.setSecurityRealm(github_realm)
    Jenkins.instance.save()
}
----

[[GitHubOAuthPlugin-Automaticallyconfigureauthorizationstrategyviascriptconsole]]
=== Automatically configure authorization strategy via script console

Configuration management could be used to configure the authorization
strategy via the
https://wiki.jenkins-ci.org/display/JENKINS/Jenkins+Script+Console[Jenkins
Script Console]. Here's a sample configuring plugin version 0.22.

[source,syntaxhighlighter-pre]
----
import org.jenkinsci.plugins.GithubAuthorizationStrategy
import hudson.security.AuthorizationStrategy

//permissions are ordered similar to web UI
//Admin User Names
String adminUserNames = 'samrocketman'
//Participant in Organization
String organizationNames = ''
//Use Github repository permissions
boolean useRepositoryPermissions = true
//Grant READ permissions to all Authenticated Users
boolean authenticatedUserReadPermission = false
//Grant CREATE Job permissions to all Authenticated Users
boolean authenticatedUserCreateJobPermission = false
//Grant READ permissions for /github-webhook
boolean allowGithubWebHookPermission = false
//Grant READ permissions for /cc.xml
boolean allowCcTrayPermission = false
//Grant READ permissions for Anonymous Users
boolean allowAnonymousReadPermission = false
//Grant ViewStatus permissions for Anonymous Users
boolean allowAnonymousJobStatusPermission = false

AuthorizationStrategy github_authorization = new GithubAuthorizationStrategy(adminUserNames,
    authenticatedUserReadPermission,
    useRepositoryPermissions,
    authenticatedUserCreateJobPermission,
    organizationNames,
    allowGithubWebHookPermission,
    allowCcTrayPermission,
    allowAnonymousReadPermission,
    allowAnonymousJobStatusPermission)

//check for equality, no need to modify the runtime if no settings changed
if(!github_authorization.equals(Jenkins.instance.getAuthorizationStrategy())) {
    Jenkins.instance.setAuthorizationStrategy(github_authorization)
    Jenkins.instance.save()
}
----

[[GitHubOAuthPlugin-OpenTickets(bugsandfeaturerequests)]]
== Open Tickets (bugs and feature requests)

[[refresh-module--2064772013]]
[[refresh--2064772013]][[jira-issues--2064772013]]
Key

Summary

T

Created

Updated

Due

Assignee

Reporter

P

Status

Resolution

[.refresh-action-group]# #

[[refresh-issues-loading--2064772013]]
[.aui-icon .aui-icon-wait]#Loading...#

[#refresh-issues-button--2064772013]##
[#refresh-issues-link--2064772013]#Refresh#
[#error-message--2064772013 .error-message .hidden]# #

[[GitHubOAuthPlugin-Releasenotes]]
== Release notes

https://github.com/jenkinsci/github-oauth-plugin/blob/master/CHANGELOG.md[See
CHANGELOG].
