A Jenkins plugin to send a docker build  request to
https://aka.ms/acr/build[Azure Container Registry].

[[AzureContainerRegistryTasksPlugin-Howtoinstall]]
== How to install

You can install/update this plugin in Jenkins update center (Manage
Jenkins -> Manage Plugins, search Azure Container Registry Tasks
Plugin).

You can also manually install the plugin if you want to try the latest
feature before it's officially released. To manually install the plugin:

. Clone the repo and build:
+
....
mvn package
....
. Open your Jenkins dashboard, go to Manage Jenkins -> Manage Plugins.
. Go to Advanced tab, under Upload Plugin section, click Choose File.
. Select `+azure-container-registry-tasks.hpi+` in `+target+` folder of
your repo, click Upload.
. Restart your Jenkins instance after install is completed. +
 +

[[AzureContainerRegistryTasksPlugin-SendAzureContainerRegistryquicktask]]
== Send Azure Container Registry quick task

[[AzureContainerRegistryTasksPlugin-Prerequisites]]
=== Prerequisites

To use this plugin to send Azure Container Registry quick tasks, first
you need to have an Azure Service Principal in your Jenkins instance.

. Create an Azure Service Principal
through https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?toc=%2fazure%2fazure-resource-manager%2ftoc.json[Azure
CLI] or https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal[Azure
portal].
. Open Jenkins dashboard, go to Credentials, add a new Microsoft Azure
Service Principal with the credential information you just created.

Then create a Container Registry in Azure portal or through Azure CLI,

[[AzureContainerRegistryTasksPlugin-SendaquicktasktoAzure]]
=== Send a quick task to Azure

You can send a quick task with your source code in following format:

. A GitHub repository, with specific branch and path.
. A local directory.
. A public remote tar.gz file

[[AzureContainerRegistryTasksPlugin-Changelog]]
== Changelog

[[AzureContainerRegistryTasksPlugin-version0.6.0,2019-01-06]]
=== version 0.6.0, 2019-01-06

* Initial release
* Support queue a docker build to Azure Container Registry with GitHub
repo, local directory or public remote tar.gz file
