[[WarriorFrameworkPlugin-Description]]
== Description

[source,conf-macro,output-inline]
----
Warrior Framework Plugin allows user to integrate Warrior Automation Framework with Jenkins to execute Warrior files
----

[[WarriorFrameworkPlugin-WarriorFrameworkPlugininstallation]]
== Warrior Framework Plugin installation

{empty}1. Navigate to Manage Jenkins → Manage Plugins → Available

{empty}2. Install 'Warrior Framework Plugin'

{empty}3. Restart Jenkins to complete installation

[[WarriorFrameworkPlugin-RunningaJenkinsjobwithWarriorFrameworkPlugin]]
== Running a Jenkins job with Warrior Framework Plugin

{empty}1. In Jenkins, navigate to 'New Item' and create a new Job

{empty}2. In Build section, click 'Add build step', and select 'Warrior
Framework Plugin'

{empty}3. Provide values for all required fields(* indicates mandatory
field) - refer 'Configuration' section below

{empty}4. Save the changes and click 'Build Now' to run the Job

[[WarriorFrameworkPlugin-Features:]]
== Features:

{empty}1. Execute warrior files(case/suite/project)

{empty}2. Upload the execution logs to FTP/SFTP/SCP server

[[WarriorFrameworkPlugin-Configuration:]]
== Configuration:

Plugin has below sections:

[[WarriorFrameworkPlugin-1.Configurationdetails(mandatory):]]
=== 1. Configuration details(mandatory):

https://github.com/warriorframework/warriorframework/tree/master/warhorn[Warhorn]
will be used for setting up the execution environment for
https://github.com/warriorframework/warriorframework[Warrior
Framework] and the details of configuration/input file for warhorn will
be specified in this section.

Configuration file can be downloaded either from a git repository or via
SFTP.

[[WarriorFrameworkPlugin-2.Filestorun(mandatory):]]
=== 2. Files to run(mandatory):

Provide relative/absolute path of warrior files - case/suite/project to
be executed by Warrior Framework

[[WarriorFrameworkPlugin-3.Pythonpath(optional):]]
=== 3. Python path(optional):

Provide the absolute path of Python interpreter or the default python
will be used for execution.

[[WarriorFrameworkPlugin-4.CopyWarriorlogfilestoremoteserver(optional):]]
=== 4. Copy Warrior log files to remote server(optional):

Provide the details of the system where the log files will be uploaded
using FTP/SFTP/SCP

Note - Click the help(?) button in the plugin to know more about each
field.

[[WarriorFrameworkPlugin-Change-log]]
== Change-log

[[WarriorFrameworkPlugin-Release1.2]]
=== Release 1.2

* Minor changes

[[WarriorFrameworkPlugin-Release1.1]]
=== Release 1.1

* Minor changes

[[WarriorFrameworkPlugin-Release1.0]]
=== Release 1.0

* Initial release of the plugin
