[[DescriptionColumnPlugin-DescriptionColumnPlugin]]
== Description Column Plugin

 +

Provide job description column for views.

[[DescriptionColumnPlugin-Configuration]]
=== Configuration

Create a new view by clicking on the "+" tab, select list view as type
and name it. At the bottom of the configuration page of the new view you
can add the Description column. +
If you want to add columns to the *All* view, follow the guide on the
https://wiki.jenkins-ci.org/display/JENKINS/Editing+or+Replacing+the+All+View[Editing
or Replacing the All View] wiki page.

You can optionnaly choose to trim the description to a certain amount of
lines by checking the appropriate checkbox and setting the request
amount. +
The trimming is done on <br/> tags

[[DescriptionColumnPlugin-Screenshots]]
=== Screenshots

Coming soon.

 +

'''''

 +

[[DescriptionColumnPlugin-Changelog]]
=== Changelog

[[DescriptionColumnPlugin-1.3(26Aug,2011)]]
==== *1.3 (26 Aug, 2011)*

* Allow to display the job name above the description.
* Added french localization.

[[DescriptionColumnPlugin-1.2(20Aug,2011)]]
==== 1.2 (20 Aug, 2011)

* Allow to limit the number of lines to display.
* Display the full description as tooltip.
* Added help on configuration.
* Added some basic tests.

[[DescriptionColumnPlugin-1.1(14Aug,2011)]]
==== 1.1 (14 Aug, 2011)

* Fix pom.xml

[[DescriptionColumnPlugin-1.0(13Aug,2011)]]
==== 1.0 (13 Aug, 2011)

* initial implementation
