Azure Dev Spaces Plugin helps to manage dev spaces
in https://docs.microsoft.com/en-us/azure/dev-spaces/[Azure Dev Spaces].

[[AzureDevSpacesPlugin-HowtoInstall]]
== How to Install

You can install/update this plugin in Jenkins update center (Manage
Jenkins -> Manage Plugins, search Azure Dev Spaces Plugin).

You can also manually install the plugin if you want to try the latest
feature before it's officially released. +
To manually install the plugin:

. Clone the repo and build:
+
[source,syntaxhighlighter-pre]
----
mvn package
----
. Open your Jenkins dashboard, go to Manage Jenkins -> Manage Plugins.
. Go to Advanced tab, under Upload Plugin section, click Choose File.
. Select `azure-dev-spaces.hpi` in `target` folder of your repo, click
Upload.
. Restart your Jenkins instance after install is completed.

[[AzureDevSpacesPlugin-Prerequisites]]
== Prerequisites

To use this plugin to manage dev spaces, first you need to have an Azure
Service Principal in your Jenkins instance.

. Create an Azure Service Principal
through https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?toc=%2fazure%2fazure-resource-manager%2ftoc.json[Azure
CLI] or
https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal[Azure
Portal].
. Open Jenkins dashboard, go to Credentials, add a new Microsoft Azure
Service Principal with the credential information you just created.

[[AzureDevSpacesPlugin-Createadevspace]]
== Create a dev space

[[AzureDevSpacesPlugin-Freestylejob]]
=== Freestyle job

. Choose to add a `Build` action 'Create dev spaces'.
. Select your Azure credential in Azure credential section.
. Select the resource group and Azure kubernetes service in your
subscription.
. Set value for your parent dev space name and dev space name.
. In the "Kubeconfig" dropdown, select the kubeconfig stored in Jenkins.
You can click the "Add" button on the right to add new kubeconfig (Kind:
Kubernetes configuration (kubeconfig)). You can enter the kubeconfig
content directly in it.

[[AzureDevSpacesPlugin-Pipeline]]
=== Pipeline

Pipeline step command is like below, follow freestyle job to fill
variables.

[source,syntaxhighlighter-pre]
----
devSpacesCreate aksName: '', azureCredentialsId: '', resourceGroupName: '', sharedSpaceName: '', spaceName: ''
----

[[AzureDevSpacesPlugin-Cleanupadevspace]]
== Clean up a dev space

[[AzureDevSpacesPlugin-Freestylejob.1]]
=== Freestyle job

. Choose to add a `Post-build Actions` action 'Cleanup dev spaces'.
. Select your Azure credential in Azure credential section.
. Select the resource group and Azure kubernetes service in your
subscription.
. Set value for dev space name needed to be cleaned up.
. In the "Kubeconfig" dropdown, select the kubeconfig stored in Jenkins.
You can click the "Add" button on the right to add new kubeconfig (Kind:
Kubernetes configuration (kubeconfig)). You can enter the kubeconfig
content directly in it.
. Save the project and build it.

[[AzureDevSpacesPlugin-Pipeline.1]]
=== Pipeline

Pipeline step command is like below, follow freestyle job to fill
variables.

[source,syntaxhighlighter-pre]
----
devSpacesCleanup aksName: '', azureCredentialsId: '', devSpaceName: '', resourceGroupName: ''
----
