Library plugin for DSL plugins that need concise names for Jenkins
extensions

[[Structsplugin-Overview]]
== Overview

Jenkins has many DSL like plugins that require having short concise
names for implementations of the extension points and other Jenkins
objects. For example,
https://wiki.jenkins-ci.org/display/JENKINS/Job+DSL+Plugin[Job DSL
Plugin] refers to each `+SCM+` extension by its short name. The same
goes for pipeline plugin.

It benefits users that these DSL plugins use consistent names. This
plugin, together with the `+@Symbol+` annotation, allow plugin
developers to name their extension and have all the DSL plugins
recognize them.

[[Structsplugin-Usagefordeveloperscreatinganyplugins]]
== Usage for developers creating any plugins

To allow all the DSL plugins to refer to your extensions by the same
name, put `+@Symbol+` annotation along side your `+@Extension+`. The
symbol name must be a valid Java identifier, and it should be short and
concise. To keep the symbol name short, it needs to be only unique
within the extension point. For example, `+GitSCM+` and
`+GitToolInstaller+` should both have a symbol name `+git+`, because
they are from different extension points. For compatibility reasons with
DSL plugins that predates the structs plugin, some extensions may have
legacy names that do not follow this convention.

[source,syntaxhighlighter-pre]
----
public class GitSCM {
   ...

   @Extension @Symbol("git")
   public static class DescriptorImpl extends SCMDescriptor {
      ...
   }
}
----

If you are targeting 1.x version of Jenkins, you must also add the
following dependency to your plugin POM:

....
    <dependency>
        <groupId>org.jenkins-ci.plugins</groupId>
        <artifactId>structs</artifactId>
        <version>1.2</version>
    </dependency>
....

[[Structsplugin-UsageforDSLplugindevelopers]]
== Usage for DSL plugin developers

Look up an extension by its symbol:

[source,syntaxhighlighter-pre]
----
@Extension @Symbol("foo")
public class FooGlobalConfiguration extends GlobalConfiguration {
   ...
}

// this yields the FooGlobalConfiguration instance
SymbolLookup.get().find(GlobalConfiguration.class,"foo")
----

Construct a `+Describable+` object from a key/value pairs, much like how
https://wiki.jenkins-ci.org/display/JENKINS/Structured+Form+Submission[Structured
Form Submission] does it via `+@DataBoundConstructor+`:

[source,syntaxhighlighter-pre]
----
new DescribableModel(Mailer.class).instantiate(Collections.singletonMap("recipients","kk@kohsuke.org"))
----

[[Structsplugin-Changelog]]
== Changelog

[[Structsplugin-Version1.20(Jul29,2019)]]
=== Version 1.20 (Jul 29, 2019)

* [.jira-issue .conf-macro .output-block]#
https://issues.jenkins-ci.org/browse/JENKINS-33217[[.aui-icon .aui-icon-wait .issue-placeholder]##
##JENKINS-33217] - [.summary]#Getting issue details...#
[.aui-lozenge .aui-lozenge-subtle .aui-lozenge-default .issue-placeholder]#STATUS#
# Log a warning when additional parameters are passed into
`DescribableModel` objects, such as Pipeline steps, since these
parameters are currently being ignored.
* Internal - Update parent pom
(https://github.com/jenkinsci/structs-plugin/pull/46[PR-46]) and fix
unit tests (https://github.com/jenkinsci/structs-plugin/pull/50[PR-50])

[[Structsplugin-Version1.19(?)]]
=== Version 1.19 (?)

* TODO

[[Structsplugin-Version1.18(Apr25,2019)]]
=== Version 1.18 (Apr 25, 2019)

* [.jira-issue .conf-macro .output-block]#
https://issues.jenkins-ci.org/browse/JENKINS-44892[[.aui-icon .aui-icon-wait .issue-placeholder]##
##JENKINS-44892] - [.summary]#Getting issue details...#
[.aui-lozenge .aui-lozenge-subtle .aui-lozenge-default .issue-placeholder]#STATUS#
#  Add new `+CustomDescribableModel+` API to allow custom instantiation
and uninstantiation for `+DescribableModel+` for advanced use cases.

[[Structsplugin-Version1.17(Oct05,2018)]]
=== Version 1.17 (Oct 05, 2018)

* [.jira-issue .conf-macro .output-block]#
https://issues.jenkins-ci.org/browse/JENKINS-53917[[.aui-icon .aui-icon-wait .issue-placeholder]##
##JENKINS-53917] - [.summary]#Getting issue details...#
[.aui-lozenge .aui-lozenge-subtle .aui-lozenge-default .issue-placeholder]#STATUS#
#  Reverting change in 1.16.

[[Structsplugin-Version1.16(Oct04,2018)]]
=== Version 1.16 (Oct 04, 2018)

* Analysis problems with `+ChoiceParameterDefinition+`.

[[Structsplugin-Version1.15(Sept25,2018)]]
=== Version 1.15 (Sept 25, 2018)

* Automatically coerce `+String+` to a number or boolean when a
parameter expects a number or boolean.

[[Structsplugin-Version1.14(Feb14,2018)]]
=== Version 1.14 (Feb 14, 2018)

* Parameter handling (dependency for
https://issues.jenkins-ci.org/browse/JENKINS-37215[JENKINS-37215])

[[Structsplugin-Version1.13(Feb1,2018)]]
=== Version 1.13 (Feb 1, 2018)

* Hotfix for *sigh* Groovy-related madness, partially reverting memory
optimizations from 1.12
* Minor correction to DescribableModel caching lookup
** Eliminates any risk looking up DescribableModels if different plugins
somehow define identical but incompatible Describable classes in the
same package and class

[[Structsplugin-Version1.12(Feb1,2018)]]
=== Version 1.12 (Feb 1, 2018)

* *Major Optimizations*: +
** Cache negative-hits in Symbol lookup (i.e. "no match"), eliminating
needless classloading and iteration over classes. 
** Cache DescribableModels, eliminating classloading associated with
creation.  
** Net result: *huge* reduction in disk reads, lock contention
(classloading), CPU use, and memory garbage generated.
* Minor optimization: reduce memory use and garbage generation
(collection pre-sizing and use of Singleton collections)
* https://issues.jenkins-ci.org/browse/JENKINS-46122[JENKINS-46122]
Report base class name when symbol couldn't be resolved

[[Structsplugin-Version1.10(Aug03,2017)]]
=== Version 1.10 (Aug 03, 2017)

* Javadoc improvements.
* Adjusting `+annotation-indexer+` version to match current core
baseline, avoiding POM warnings in plugins depending on this one.

[[Structsplugin-Version1.9(Jun26,2017)]]
=== Version 1.9 (Jun 26, 2017)

* http://45130@issue/[JENKINS-45130] When uninstantiating, qualify
otherwise ambiguous class names for array and list properties.

[[Structsplugin-Version1.8(Jun15,2107)]]
=== Version 1.8 (Jun 15, 2107)

* http://44864@issue/[JENKINS-44864] When uninstantiating, suppress
values from `+@Deprecated+` setters where the values have no effect on
the resulting object. 

[[Structsplugin-Version1.7(May25,2017)]]
=== Version 1.7 (May 25, 2017)

* https://issues.jenkins-ci.org/browse/JENKINS-43337[JENKINS-43337] Snippet
generation should qualify otherwise ambiguous class names.
* https://issues.jenkins-ci.org/browse/JENKINS-34464[JENKINS-34464] Allow
binding of parameters of type `+Result+`, for example in
the `+upstream+` trigger.
* https://issues.jenkins-ci.org/browse/JENKINS-31967[JENKINS-31967] Handle
remaining primitive types for parameters, for example `+double+`
in `+junit+` configuration.

[[Structsplugin-Version1.6(Feb13,2017)]]
=== Version 1.6 (Feb 13, 2017)

* https://issues.jenkins-ci.org/browse/JENKINS-38157[JENKINS-38157]
Better diagnostics.
* Allow Groovy `+GString+` to be used in more places.
* API to check deprecation status of a type.

[[Structsplugin-Version1.5(Aug30,2016)]]
=== Version 1.5 (Aug 30, 2016)

* https://issues.jenkins-ci.org/browse/JENKINS-37820[JENKINS-37820]
Stack overflow in 1.4 under certain conditions.

[[Structsplugin-Version1.4(Aug26,2016)]]
=== Version 1.4 (Aug 26, 2016)

* https://issues.jenkins-ci.org/browse/JENKINS-37403[JENKINS-37403] API
for getting `+@Symbol+` off an `+Object+`.

[[Structsplugin-Version1.3(Jul28,2016)]]
=== Version 1.3 (Jul 28, 2016)

* https://issues.jenkins-ci.org/browse/JENKINS-29922[JENKINS-29922]
Support for `+@Symbol+` in `+DescribableModel+`.

[[Structsplugin-Version1.2.0(Jun17,2016)]]
=== Version 1.2.0 (Jun 17, 2016)

* image:docs/images/add.svg[(plus)]
Added method to query deprecated methods
(https://github.com/jenkinsci/structs-plugin/pull/5[PR #5])
* image:docs/images/error.svg[(error)]
Improve diagnostics for mismatched types
(https://issues.jenkins-ci.org/browse/JENKINS-34070[JENKINS-34070])
* image:docs/images/error.svg[(error)]
Prevent recursions in the DescribableModel.toString() method
(https://github.com/jenkinsci/structs-plugin/pull/3[PR #3], related to
https://issues.jenkins-ci.org/browse/JENKINS-32925[JENKINS-32925])

[[Structsplugin-Version1.1.1(Jun16,2016)]]
=== Version 1.1.1 (Jun 16, 2016)

* image:docs/images/error.svg[(error)]
Fix URL to the plugin's Wiki page in order to get it listed in Jenkins
Update Center again
(https://issues.jenkins-ci.org/browse/JENKINS-JENKINS-35918[JENKINS-JENKINS-35918])

[[Structsplugin-Version1.1(Mar22,2016)]]
=== Version 1.1 (Mar 22, 2016)

* image:docs/images/information.svg[(info)]
Many small commits made by
https://wiki.jenkins-ci.org/display/~kohsuke[Unknown User (kohsuke)]

[[Structsplugin-Version1.0(Mar18,2016)]]
=== Version 1.0 (Mar 18, 2016)

* initial version
