[[JDependPlugin-Introduction]]
== Introduction

The JDepend Plugin is a plugin to generate JDepend reports for builds.

[[JDependPlugin-Quickstart]]
== Quickstart

. Download the JDepend plugin from the Update Center
. Enable for a project by checking "Report JDepend" under the
"Post-build actions" of your project
. Run a build
. View the build page once it has completed, and you should see a
"JDepend" entry on the left sidebar.

[[JDependPlugin-Notes]]
== Notes

The JDepend plugin does not currently report the health of a project, as
the sheer number of metrics available in a JDepend report makes it very
difficult to find any sort of reasonable estimate of what makes a
healthy project. This is one of the times when human intuition might be
best!

[[JDependPlugin-Bugreporting]]
== Bug reporting

Please direct all bugs to the http://issues.jenkins-ci.org/[issue
tracker], making sure to mention "JDepend" somewhere in the heading or
body. Bugs will continue to be looked at and fixed (features will not).
For faster resolution, assign 'lewisham' to the bug.

[[JDependPlugin-Featurerequests]]
== Feature requests

Please direct all feature requests to the
http://issues.jenkins-ci.org/[issue tracker], making sure to mention
"JDepend" somewhere in the heading or body. Please note that active
development on this plugin has ceased for the time being (the original
itch has been scratched), so if you have new features, it will be
quicker to try having a go yourself and make a commit to the SVN
repository. The code should be fairly good.

[[JDependPlugin-Developmenthistory]]
== Development history

[[JDependPlugin-Version1.3.0(Feb22,2018)]]
=== Version 1.3.0 (Feb 22, 2018)

* https://issues.jenkins-ci.org/browse/JENKINS-49586[JENKINS-49586] -
Make the plugin compatible with Jenkins 2.102+ +
** More
info: https://wiki.jenkins.io/display/JENKINS/Plugins+affected+by+fix+for+JEP-200[Plugins
affected by fix for JEP-200]
* https://github.com/jenkinsci/jdepend-plugin/commit/0c8fbfa25f1dac94b1df242578b12da2cd4ac7ec[Commit]
- Create JDepend temporary directory on master (reverts change in 1.2.4)
** Note from https://wiki.jenkins.io/display/~oleg_nenashev[Unknown User
(oleg_nenashev)]: This was a pending commit in the master branch. If you
experience any issues with that, raise a JIRA ticket

[[JDependPlugin-Version1.2.4(Nov03,2014)]]
=== Version 1.2.4 (Nov 03, 2014)

* https://github.com/jenkinsci/jdepend-plugin/commit/967b803b52c50d900408de10ad8535f4716af821[Commit]
- Create JDepend temporary directory on agent instead of the master

[[JDependPlugin-Version1.2.3(Feb14,2011)]]
=== Version 1.2.3 (Feb 14, 2011)

* Remove unused code.

[[JDependPlugin-Version1.2.2(Sep17,2009)]]
=== Version 1.2.2 (Sep 17, 2009)

* Fixed config file growth.
(https://issues.jenkins-ci.org/browse/JENKINS-4494[JENKINS-4494])

[[JDependPlugin-Version1.2.1(Aug29,2009)]]
=== Version 1.2.1 (Aug 29, 2009)

* Added relative path to workspace as a possible configuration. No
compatibility for Ant-style FileSets though, there should only be one
JDepend report.

[[JDependPlugin-Version1.2]]
=== Version 1.2

* Use existing JDepend XML file.
(https://issues.jenkins-ci.org/browse/JENKINS-4083[JENKINS-4083])

Version 1.0 was developed by Chris Lewis (lewisham). Development of
version 1.0 of this plugin was made possible by the National Science
Foundation and released under the BSD license from the University of
California, Santa Cruz. If you like it, remember to keep voting for the
public funding of scientific and educational facilities!
