Keeps build artifacts compressed to save disk space on the master.

Adds an option to compress build artifacts (currently in a ZIP file
only) when stored on the master. To use, you must request this option in
the Jenkins global configuration screen (_Artifact Management for
Builds_ section).

Artifacts produced before the plugin was installed/configured will not
be compressed, though it will be served correctly.

Compatibility issues

[.aui-icon .aui-icon-small .aui-iconfont-warning .confluence-information-macro-icon]#
#

Some other plugins do not yet support nonstandard artifact storage. In
particular, Copy Artifact will be broken.
(https://issues.jenkins-ci.org/browse/JENKINS-22637[JENKINS-22637])

[[CompressArtifactsPlugin-Changelog]]
== Changelog

[[CompressArtifactsPlugin-Version1.7]]
=== Version 1.7

* Optimize artifact archiving.
(https://issues.jenkins-ci.org/browse/JENKINS-28862[JENKINS-28862])
* Fix regression of
https://issues.jenkins-ci.org/browse/JENKINS-27042[JENKINS-27042] from
1.6.

[[CompressArtifactsPlugin-Version1.5]]
=== Version 1.5

* Unable to compress artifacts with non-IBM437 characters in filename.
Regression introduced in 1.4.
(https://issues.jenkins-ci.org/browse/JENKINS-27522[JENKINS-27522])

[[CompressArtifactsPlugin-Version1.4]]
=== Version 1.4

* java.util.zip.ZipException thrown when reading artifacts from archive
larger than 4G.
(https://issues.jenkins-ci.org/browse/JENKINS-27042[JENKINS-27042])

Stability issues

[.aui-icon .aui-icon-small .aui-iconfont-warning .confluence-information-macro-icon]#
#

Before this version, plugin is not able to serve artifacts when archive
exceeds 4G in size, it leads to JVM crashes on java 6.
(https://issues.jenkins-ci.org/browse/JENKINS-27042[JENKINS-27042])

[[CompressArtifactsPlugin-Version1.3]]
=== Version 1.3

* Avoid ZipException thrown when accessing artifiacts while archiving.
https://github.com/jenkinsci/compress-artifacts-plugin/commit/47208791705ed6d77bbc4931fe8f1f4517c9b9bc[4720879]

[[CompressArtifactsPlugin-Version1.2]]
=== Version 1.2

* Handle special characters in artifact filename correctly.
https://issues.jenkins-ci.org/browse/JENKINS-26858[JENKINS-26858]

[[CompressArtifactsPlugin-Version1.1]]
=== Version 1.1

* Supporting “download artifacts as ZIP”.

[[CompressArtifactsPlugin-Version1.0]]
=== Version 1.0

* Initial version. See
https://issues.jenkins-ci.org/browse/JENKINS-6229[JENKINS-6229] for
background. Not yet implemented: adding artifacts in multiple rounds;
downloading ZIPs of artifacts.
