Allow you to run eXtensive Testing tests before or after a build.

[.conf-macro .output-inline]# #

[.aui-icon .aui-icon-small .aui-iconfont-error .confluence-information-macro-icon]##

The current version of this plugin may not be safe to use. Please review
the following warnings before use:

* https://jenkins.io/security/advisory/2019-10-16/#SECURITY-1432[Credentials
stored in plain text]

Log test steps into log file on the project workspace. +
Show results in HTML page. +
Store results into the project workspace.

More informations about http://www.extensivetesting.org/[eXtensive
Testing] by Denis Machard.

[[ExtensiveTestingPlugin-Configuration]]
== Configuration

Go to configuration page  /job/<jobname>/configure

In the "Build" section, Add a build step : select eXtensive Testing

Enter the following parameters (don't forget a "/"):

* Extensive Testing ProjectName : the project name in xtc server _ex:
Common_

* Extensive Testing Test Path : the path to the test in xtc  _ex:
/Basics/00_Wait.tux_

* Extensive Testing Login : xtc user

* Extensive Testing Password : xtc user's password

* Extensive Testing Rest API Url : Rest API URL _ex:
[.nolink]#http://192.168.51.246/rest/#_

* Debug Mode : Enable or Disable advanced logs

[[ExtensiveTestingPlugin-Changelog]]
== Changelog
