Allows rebuilds of multibranch PR jobs based on GitHub PR comments.

[.aui-icon .aui-icon-small .aui-iconfont-error .confluence-information-macro-icon]#
#

The latest release (2.0) is meant for the 2.x SCM API-related plugins.
Upgrading to this version will bring in those plugins, so use caution to
make sure you are ready! See
https://jenkins.io/blog/2017/01/17/scm-api-2/[this blog post] for more
information.

[[GitHubPRCommentBuildPlugin-Configuration]]
== Configuration

To use the plugin, simply add a property to any branch (or all branches)
on a multibranch job. Two properties are available:

* Trigger build on pull request comment - builds the job when a pull
request comment is added/edited. You may wish to change the pattern that
is searched for when matching comments. This is a regular expression and
not a simple text match.
* Trigger build on pull request update - builds the job when the pull
request title or body is updated.

[[GitHubPRCommentBuildPlugin-Changelog]]
== Changelog

[[GitHubPRCommentBuildPlugin-2.0(June15,2017)]]
=== 2.0 (June 15, 2017)

Support newer SCM/branch source plugins. Use this release if you are
using the 2.x releases of the SCM API-related plugins.

[[GitHubPRCommentBuildPlugin-1.1(March6,2017)]]
=== 1.1 (March 6, 2017)

Add support for building a job when a PR title or body is updated as
well by using a separate branch property.

[[GitHubPRCommentBuildPlugin-1.0(January23,2017)]]
=== 1.0 (January 23, 2017)

Initial release
