[.conf-macro .output-inline]##

[cols="",options="header",]
|===
|Plugin Information
|View Azure Event Grid Build Notifier
https://plugins.jenkins.io/azure-event-grid-notifier[on the plugin site]
for more information.
|===

[.aui-icon .aui-icon-small .aui-iconfont-error .confluence-information-macro-icon]##

The current version of this plugin may not be safe to use. Please review
the following warnings before use:

* https://jenkins.io/security/advisory/2019-09-25/#SECURITY-1544[Credentials
stored in plain text]

Send build notifications to an Azure Event Grid Topic

[[AzureEventGridNotifier-HowtoInstall]]
== How to Install

You can install/update this plugin in Jenkins update center (Manage
Jenkins -> Manage Plugins, search Azure Event Grid Notifier Plugin).

You can also manually install the plugin if you want to try the latest
feature before it's officially released. To manually install the plugin:

. Clone the repo and build:
+
....
mvn package
....
. Open your Jenkins dashboard, go to Manage Jenkins -> Manage Plugins.
. Go to Advanced tab, under Upload Plugin section, click Choose File.
. Select `+azure-event-grid-notifer.hpi+` in `+target+` folder of your
repo, click Upload.
. Restart your Jenkins instance after install is completed.

[[AzureEventGridNotifier-Prerequisites]]
=== Prerequisites

To use this plugin, first you need to create
an https://docs.microsoft.com/en-us/azure/event-grid/custom-event-quickstart[Azure
Event Grid Topic]

[[AzureEventGridNotifier-Howtouse]]
=== How to use

You can define a custom subject and a custom message using environment
variables such as:

$\{BUILD_PHASE_NAME}

$\{BUILD_PHASE}

$\{BUILD_DURATION}

$\{BUILD_ARTIFACTS}

or just leave the default message and subject.

[[AzureEventGridNotifier-Changelog]]
== Changelog

[[AzureEventGridNotifier-Version0.1(2017-8-22)]]
=== Version 0.1 (2017-8-22)

* Initial release
