[.conf-macro .output-inline]##

[cols="",options="header",]
|===
|Plugin Information
|View Data Theorem: CI/CD
https://plugins.jenkins.io/datatheorem-mobile-app-security[on the plugin
site] for more information.
|===

[.aui-icon .aui-icon-small .aui-iconfont-info .confluence-information-macro-icon]##

Older versions of this plugin may not be safe to use. Please review the
following warnings before using an older version:

* https://jenkins.io/security/advisory/2019-09-25/#SECURITY-1557[Credentials
stored in plain text]

 +

[[DataTheoremMobileAppSecurityPlugin-Purpose]]
== Purpose

This plugin allows you to automatically upload mobile applications
packages to Data Theorem's App Secure service at the end of the CI
process.

App Secure is a continuous automated security service that scans mobile
applications (iOS and Android) for security and privacy issues.

More informations about this product are available
here: https://www.datatheorem.com/products/app-secure

[[DataTheoremMobileAppSecurityPlugin-Requirements]]
== Requirements

The Jenkins minimal version requirement is 2.73.2.

The plugin also requires:

* Credential Plugin:
https://plugins.jenkins.io/credentials[https://plugins.jenkins.io/credential]
* Credential Binding
Plugin: https://plugins.jenkins.io/credentials-binding

The plugin needs a valid customer API Key from Data Theorem. To find
your API Key, you can connect
to https://www.securetheorem.com/sdlc using your Data Theorem user
account.

[[DataTheoremMobileAppSecurityPlugin-Documentation]]
== Documentation

Full plugin documentation and step by step guide is available
at: https://datatheorem.atlassian.net/servicedesk/customer/kb/view/32079873

 +

 +
