 

 [.conf-macro .output-inline]#This plugin adds a new build parameter
type for resolving artifact versions reading the repository
http://docs.codehaus.org/display/MAVEN/Repository+Metadata[maven-metadata.xml].# 

[[MavenMetadataPlugin-Description]]
== Description

In any jenkins job enable the "This build is parametrerized" checkbox,
from the drop-down that appears select the "List maven artifact
versions", configure the artifact you want to retrieve the versions for
and voilà.

[[MavenMetadataPlugin-Parameters]]
== Parameters

Because there are multiple aspects that can be of interest about an
artifact in a maven repository this plugin will not set the parameter
name you give in the configuration of your job, but will rather use that
name as a seed for a set of parameters. Example:

In your configuration you have created a parameter named "MY_JAR" and
have configured all values correctly. Then the following parameters will
be set for the build step:

* MY_JAR_VERSION - the version you selected in the dropdown or that was
selected as part of an automated build
* MY_JAR_ARTIFACT_URL - the full URL to the actual artifact selected.
You can use something like "wget" to download that artifact and do
something with it.
* MY_JAR_GROUP_ID - echoes back your configuration
* MY_JAR_ARTIFACT_ID - echoes back your configuration
* MY_JAR_CLASSIFIER - echoes back your configuration
* MY_JAR_PACKAGING - echoes back your configuration

[[MavenMetadataPlugin-Knownissues]]
== Known issues

* None at the moment.

[[MavenMetadataPlugin-UpgradeInformation]]
== Upgrade Information

[[MavenMetadataPlugin-RepositoryUsernameandPassword]]
=== Repository Username and Password

With release 1.3, the _Repository Username_ and _Repository Password_
have been migrated to _Repository Credentials_. Now, repository
credentials are stored in the global credentials. Usernames and
Passwords of previous plugin versions are automatically migrated: For
each _Repository Base URL_ and _Repository Username_ combination, a new
global credentials object will be created and referenced.

[[MavenMetadataPlugin-VersionHistory]]
=== Version History

[[MavenMetadataPlugin-2.0.0(10.January2018)]]
==== 2.0.0 (10. January 2018)

* Return param value to pipeline
* Update to Jenkins 2 to address SECURITY-170

[[MavenMetadataPlugin-1.5.0(31.May2016)]]
==== 1.5.0 (31. May 2016)

* Added support for rebuilding

[[MavenMetadataPlugin-1.4.1(14.March2016)]]
==== 1.4.1 (14. March 2016)

* Fixed severe bug that was introduced with version 1.4.0 - SORRY for
that.

[[MavenMetadataPlugin-1.4.0(04.March2016)]]
==== 1.4.0 (04. March 2016)

* Added classifier support.

[[MavenMetadataPlugin-1.3.0(10.November2015)]]
==== 1.3.0 (10. November 2015)

* Added optional configurations that allows to download and display
information about currently used artifact.
* Use Jenkins credentials to store repository username and password.
With this, passwords are encrypted and no longer stored as plain text in
the jobs _config.xml_ file.
* Bugfix: Invalid artifact URL when packaging is not specified.

[[MavenMetadataPlugin-1.2.0(26.November2014)]]
==== 1.2.0 (26. November 2014)

* Added support for SNAPSHOTs. The plugin should now properly resolve
SNAPSHOT versions to their timestamped
URLs.https://issues.jenkins-ci.org/browse/JENKINS-23206[JENKINS-23206]
* Thanks to https://github.com/mathieu-pousse[Mathieu Pousse] for
providing the pull request for this change.

[[MavenMetadataPlugin-1.1.1(14.February2014)]]
==== 1.1.1 (14. February 2014)

* Added support for the command line interface. If you have a property
named MY_JAR you should now be able to append -p MY_JAR=1.3.42 and the
job will be started for version "1.3.42" without scanning the maven
repository. All of the above mentioned parameters should still be set
for your build steps using the version you provided on the command line.
* Thanks to https://github.com/dportabella[David Portabella] for
providing the pull request for this change.

[[MavenMetadataPlugin-1.1.0(13.February2014)]]
==== 1.1.0 (13. February 2014)

* Corrected the help message. (Was copy-pasted from another plugin).
* Added a username and password fields which will override the previous
way of specifying username:password as part of URL - no need to add them
in url-encoded, plain-text to the URL.
* Thanks to https://github.com/barclay-reg[Robert
Kleinschmager] and https://github.com/imod[Dominik Bartholdi] for
providing the pull requests for these changes.

[[MavenMetadataPlugin-1.0.0(16.April2012)]]
==== 1.0.0 (16. April 2012)

* Initial version.

[[MavenMetadataPlugin-HelpandSupport]]
== Help and Support

 

For help and support please use the
http://jenkins-ci.org/content/mailing-lists[Jenkins Users] mailing
list. +
The comment list below is not monitored.

type

key

summary

[.icon-in-pdf]# # Data cannot be retrieved due to an unexpected error.

http://issues.jenkins-ci.org/secure/IssueNavigator.jspa?reset=true&jqlQuery=project%20=%20JENKINS%20AND%20status%20in%20%28Open,%20%22In%20Progress%22,%20Reopened%29%20AND%20component%20=%20%27maven-metadata-plugin%27&src=confmacro[View
these issues in Jira]
