[.conf-macro .output-inline]#A simple notifier that can publish build
notifications to a topic on a http://mqtt.org/[MQTT] broker.#

[[MQTTNotificationPlugin-About]]
== About

_http://mqtt.org/[MQTT]_ _is a machine-to-machine (M2M)/"Internet of
Things" connectivity protocol. It was designed as an extremely
lightweight publish/subscribe messaging transport. _

The following details are configurable per Jenkins job:

* Broker hostname/port
* Topic
* Message

Both the topic and the message may also include certain dynamic
variables. These include:

* PROJECT_URL - The relative URL to the Jenkins project to which this
job belongs (e.g. "job/my-build").
* BUILD_RESULT - The result of the Job (e.g. SUCCESS, FAILURE, ABORTED,
etc.)
* BUILD_NUMBER - The build number
* CULPRITS - Comma-separated list of build culprits

All other build variables and environment variables can also be
used (https://issues.jenkins-ci.org/browse/JENKINS-41839[JENKINS-41839]).

The default topic when no value is specified is "jenkins/PROJECT_URL".

The default message when no value is specified is "BULD_RESULT".

[[MQTTNotificationPlugin-Changelog]]
== Changelog

[[MQTTNotificationPlugin-1.7(2017-06-27)]]
=== 1.7 (2017-06-27)

The MqttNotifier can now be used in a jenkins pipeline, too. (Thanks
https://github.com/michaelknigge/mqtt-notification-plugin/commit/18ff49ab1b4849091060e22113caf7b119cd99cb[michaelknigge]!)

[[MQTTNotificationPlugin-1.6(2017-03-15)]]
=== 1.6 (2017-03-15)

Fixed credentials problem introduced while refactoring for unit testing
in previous release
(https://issues.jenkins-ci.org/browse/JENKINS-42764[JENKINS-42764])

[[MQTTNotificationPlugin-1.5(2017-03-06)]]
=== 1.5 (2017-03-06)

* Fixed problem with variable substitution
(https://issues.jenkins-ci.org/browse/JENKINS-41974[JENKINS-41974])
* Started using
https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/text/StrSubstitutor.html[StrSubstitutor]
for variable substitution
* Added a unit test, but it's not doing much yet. Need to improve this.

[[MQTTNotificationPlugin-1.4.2(2017-02-12)]]
=== 1.4.2 (2017-02-12)

* Reverted language level to Java 7 following failed integration test

[[MQTTNotificationPlugin-1.4.1(2017-02-12)]]
=== 1.4.1 (2017-02-12)

* Bumped pom parent version, triggered a few findbugs violations. Now
fixed.

[[MQTTNotificationPlugin-1.4(2017-02-12)]]
=== 1.4 (2017-02-12)

* MQTT Notification plugin should be able to publish build number, build
parameters
(https://issues.jenkins-ci.org/browse/JENKINS-41839[JENKINS-41839])

[[MQTTNotificationPlugin-1.3(2016-01-09)]]
=== 1.3 (2016-01-09)

* Environment variables can now be used in topic and message
(https://issues.jenkins-ci.org/browse/JENKINS-31669[JENKINS-31669])
* Guard against credentials leak
(https://issues.jenkins-ci.org/browse/JENKINS-25035[JENKINS-25035])
* Bumped Paho MQTT client version
(https://github.com/gdubya/mqtt-notification-plugin/issues/4[GitHub
issue 4])

[[MQTTNotificationPlugin-1.2.1(2016-01-06)]]
=== 1.2.1 (2016-01-06)

* No changes. Republished 1.2 as the release didn't quite make it public
for some reason.

[[MQTTNotificationPlugin-1.2(2015-06-23)]]
=== 1.2 (2015-06-23)

* I'm not dead yet!
* Bumped jenkins-ci plugin parent to 1.600
(https://issues.jenkins-ci.org/browse/JENKINS-23239[JENKINS-23239])
* Merged pull request to
https://github.com/jenkinsci/mqtt-notification-plugin/pull/2[use
credentials when testing broker connection]

[[MQTTNotificationPlugin-1.1(2013-08-15)]]
=== 1.1 (2013-08-15)

* Modified DefaultFilePersistence to use java.io.tmpdir

[[MQTTNotificationPlugin-1.0(2013-08-12)]]
=== 1.0 (2013-08-12)

* Initial release
