This plug-in makes it possible to show all the job tasks (builders,
publishers, ...) to be executed as part of a build job.

[[DryRunPlugin-Features]]
== Features

This plugin enables you to run your job in a dry-run mode. +
If build step are dry-run aware (implements DryRun extension point), the
dry-run execution is delegated to the build step. +
At the moment, the
https://wiki.jenkins-ci.org/display/JENKINS/Gradle+Plugin[Gradle Plugin]
and the https://wiki.jenkins-ci.org/display/JENKINS/xUnit+Plugin[xUnit
Plugin] provide the dry-run feature. +
And we strongly recommend other plugins to implement the DryRun
extension point.

[[DryRunPlugin-Changelog]]
== Changelog

[[DryRunPlugin-0.9]]
=== 0.9

* Fix https://issues.jenkins-ci.org/browse/JENKINS-15171[JENKINS-15171]
- The run button must respect the configured rights

[[DryRunPlugin-0.8]]
=== 0.8

* Add a default Jenkins Result as SUCCESS for plugin using dry-un

[[DryRunPlugin-0.7]]
=== 0.7

* Fix dry-run builders

[[DryRunPlugin-0.6]]
=== 0.6

* Add a job property (Enable to choice different types of dry-run for
the the job: runlisteners, buildwrappers, builders, ...)

[[DryRunPlugin-0.5]]
=== 0.5

* Remove the dry-run for the maven job type (the maven job type Jenkins
implementation is not suitable for a well dry-run)

[[DryRunPlugin-0.4]]
=== 0.4

* Added dry-run for publishers

[[DryRunPlugin-0.3]]
=== 0.3

* Added a badge action to the build history

[[DryRunPlugin-0.2]]
=== 0.2

* Delegate dry-un to the build step if the build step extends DryRun
extension point.

[[DryRunPlugin-0.1]]
=== 0.1

* Initial version
