 +

This plugin show information about jobs, slaves and the queue in
Jenkins.

The JQS-Monitoring Plugin makes it possible to monitor what is happening
in the job queue, what is the status of each slave or each job that is
being build at the moment. You can also get information about the number
of failed builds for the last 24 hours in a histogram graphic. With the
plugin you can easily detect if a job is stuck in the queue or being
built for too long. The information for the different components can be
viewed separately in single pages or simultaneously in one big page. The
links to this pages can be found in the left menu-panel of the plugin.

This menu-panel also contains a link to the configuration page, where a
number of options can be configured to change the way information is
shown(size, color, hide/show options).

[[JQSMonitoringPlugin-Usage]]
== Usage

The plugin can be used to show information on small or big monitors, the
different components can be added to other pages using the links.

For example you can use iframes to continuously monitor several Jenkins
instances.

The plugin will appear in the left-side panel of the jenkins homepage.
Its icon and links are available only for users with administrator
permission.

[[JQSMonitoringPlugin-Openissues]]
== Open issues

[[refresh-module-1705746212]]
[[refresh-1705746212]][[jira-issues-1705746212]]
T

Key

Summary

Assignee

Reporter

P

Status

Resolution

Created

Updated

Due

[.refresh-action-group]# #

[[refresh-issues-loading-1705746212]]
[.aui-icon .aui-icon-wait]#Loading...#

[#refresh-issues-button-1705746212]##
[#refresh-issues-link-1705746212]#Refresh#
[#error-message-1705746212 .error-message .hidden]# #

[[JQSMonitoringPlugin-Changelog]]
== Change log

[[JQSMonitoringPlugin-Version1.4-(07.10.2013)]]
=== Version 1.4 - (_07.10.2013_)

* Show count for offline slaves

[[JQSMonitoringPlugin-Version1.3-(19.07.2013)]]
=== Version 1.3 - (_19.07.2013_)

* REST API shows more information

[[JQSMonitoringPlugin-Version1.2-(26.06.2013)]]
=== Version 1.2 - (_26.06.2013_)

* Fixed problem where in some cases the number of failed jobs was lower
that the actual.
* Fixed problem when retrieving the jenkins root path.
* Unnecessary code deleted.

[[JQSMonitoringPlugin-Version1.0-(18.04.2013)]]
=== Version 1.0 - (_18.04.2013_)

* First release.

[[JQSMonitoringPlugin-About]]
== About

  The plugin is open source.
