[.conf-macro .output-inline]# #

[.aui-icon .aui-icon-small .aui-iconfont-info .confluence-information-macro-icon]##

Older versions of this plugin may not be safe to use. Please review the
following warnings before using an older version:

* https://jenkins.io/security/advisory/2018-02-26/#SECURITY-260[Keystore
and private key passwords stored in plain text]

[.conf-macro .output-inline]#This plugin integrates Jenkins with
the http://www.coverity.com/products/coverity-connect/[Coverity
Connect] and http://www.coverity.com/products/code-advisor/[Coverity
Static Analysis] tools.#

[[CoverityPlugin-Documentation]]
== Documentation

https://github.com/jenkinsci/coverity-plugin[Please find documentation
on GitHub README]

 +

[.aui-icon .aui-icon-small .aui-iconfont-error .confluence-information-macro-icon]#
#

*This plugin is no longer maintained and will be deprecated by
11/30/2018. The functionality has been migrated onto the
new https://github.com/jenkinsci/synopsys-coverity-plugin[Synopsys
Coverity Jenkins plugin]. Please download the new plugin from GitHub or
search for “Synopsys Coverity Jenkins" plugin under “Manage plugins” on
your Jenkins system to install it directly. Please
contact software-integrity-support@synopsys.com for any issues.
 Official support for this implementation ends on 06/30/2019.”*

[[CoverityPlugin-Support]]
== Support

If you have any questions or issues with the Coverity plugin,
contact coverity-support@synopsys.com
