[.conf-macro .output-inline]# #

[.aui-icon .aui-icon-small .aui-iconfont-error .confluence-information-macro-icon]##

The current version of this plugin may not be safe to use. Please review
the following warnings before use:

* https://jenkins.io/security/advisory/2019-09-25/#SECURITY-1548[Credentials
stored in plain text]

[[CallRemoteJobPlugin-Description]]
== Description

Call Remote Job Plugin is for call remote jenkins job. +
Word starts With "$" in name, password and parameter is able to replace
with build parameter. +
ex: parameter is "param1=$buildParam1&param2$buildParam2" and build
parameter "param1:value1" and "param2:value2", +
parameter is replaced as param1=value1&param2=value2 on execute.

Call Remote Job PluginはリモートのJenkins
Jobを呼び出すためのプラグインです。

nameとpasswordとparameter中に$で始まる文字があると、同名のbuild
parameterで置換します。 +
Call Remote Job
Pluginのパラメーターに　"param1=$buildParam1&param2$buildParam2"　というのがあって、 +
ビルドパラメータに"param1:value1" と、
"param2:value2"　というのがあると、 +
リモートのJobを呼び出すときにはパラメータは
"param1=value1&param2=value2" になります。

[[CallRemoteJobPlugin-Versionhistory]]
== Version history

[width="100%",cols="34%,33%,33%",options="header",]
|===
|version |information |date
|1.0.12 |new release |2013/06/21

|1.0.16 |add description |2013/06/23 +

|1.0.18 |bug
fixed(https://issues.jenkins-ci.org/browse/JENKINS-18616[JENKINS-18616])
|2013/07/04

|1.0.19 |name,password,parameter are able to replace with build
parameter. |2013/07/30

|1.0.20 |bug fixed on handle same long build parameter . |2013/07/31

|1.0.21 |Enviroment parameter are replace config. |2013/12/13

|  |  | 
|===
