[.conf-macro .output-inline]# #

[.aui-icon .aui-icon-small .aui-iconfont-warning .confluence-information-macro-icon]##

*This plugin is up for adoption.* Want to help improve this plugin?
https://wiki.jenkins.io/display/JENKINS/Adopt+a+Plugin[Click here to
learn more]!

View type to allow grouping job views into multiple levels instead of
one big list of tabs.

This plugin adds a new view type that can be selected when adding job
views. This view does not show any jobs, but rather contains another set
of views. By default, clicking on the view tab for a nested view shows a
list of the subviews it contains (with folder icons). You can also
configure a default subview to bypass this intermediate page and jump
directly to that default view. Now the view tabs across the top show the
views in this nested view, and the job list is for this default subview.
This streamlines the navigation between views, but makes it harder to
find the _Edit View_ link for the nested view itself. Once a default
subview has been assigned, navigate to the edit page by first clicking
the plus ("+") icon in the view tabs (for adding a new subview) and then
find the _Edit View_ link in the sidepanel.

Note, that starting from 1.10 columns Status and Weather are switched
off by default because of issues with performance, but if you'd like to
have them, just edit your view and add respective columns.

'''''

[[NestedViewPlugin-ChangeLog]]
== Change Log

[[NestedViewPlugin-Version1.14(November23,2013)]]
=== Version 1.14 (November 23, 2013)

* Improve breadcrumb list behavior
(https://issues.jenkins-ci.org/browse/JENKINS-19698[JENKINS-19698],https://issues.jenkins-ci.org/browse/JENKINS-20616[JENKINS-20616])

[[NestedViewPlugin-Version1.13(November5,2013)]]
=== Version 1.13 (November 5, 2013)

* Fixed view results to be gray if no jobs were run in subviews yet
(https://issues.jenkins-ci.org/browse/JENKINS-17040[issue #17040])
* Fixed deleting of subviews (it didn't save on disk)
(https://issues.jenkins-ci.org/browse/JENKINS-20382[issue #20382])

[[NestedViewPlugin-Version1.12(October30,2013)]]
=== Version 1.12 (October 30, 2013)

* Fixed view results (aggregating of subviews and jobs) to follow the
correct priority - if at least one job is red, then the view will be red
(https://issues.jenkins-ci.org/browse/JENKINS-19716[issue #19716])

[[NestedViewPlugin-Version1.11(September25,2013)]]
=== Version 1.11 (September 25, 2013)

* Fixed creation of subviews if Nested View is the default one
(https://issues.jenkins-ci.org/browse/JENKINS-17041[JENKINS-17041])
* Support checking duplicate names with jenkins 1.512 or newer
(https://issues.jenkins-ci.org/browse/JENKINS-18053[JENKINS-18053])

[[NestedViewPlugin-Version1.10(April7,2013)]]
=== Version 1.10 (April 7, 2013)

* Added an ability to remove or add Weather and Status columns which
speeds up nested views
(https://issues.jenkins-ci.org/browse/JENKINS-17352[JENKINS-17352])

[[NestedViewPlugin-Version1.9(August16,2012)]]
=== Version 1.9 (August 16, 2012)

* Improved performance and accuracy when computing worst result and
health for large views
* add support for hierarchical job model (ex : cloudbees folder plugin)
* display grey icon when no nested content has been built

[[NestedViewPlugin-Version1.8(Jul28,2011)]]
=== Version 1.8 (Jul 28, 2011)

* Properly check for duplicate names within the current nested view when
creating a new view (in Jenkins 1.416 or newer).
* Ignore disabled project when calculating worst build result in a
nested view.
(https://issues.jenkins-ci.org/browse/JENKINS-8922[JENKINS-8922])

[[NestedViewPlugin-Version1.7(Feb25,2011)]]
=== Version 1.7 (Feb 25, 2011)

* Rerelease 1.6 to properly set required Jenkins version.

[[NestedViewPlugin-Version1.6(Feb16,2011)]]
=== Version 1.6 (Feb 16, 2011)

* Show status icon for each view, representing the worst result of any
job in that view.
(https://issues.jenkins-ci.org/browse/JENKINS-7124[JENKINS-7124])
* Fix link in empty nested view to be a link instead of raw HTML.
(https://issues.jenkins-ci.org/browse/JENKINS-7862[JENKINS-7862])

[[NestedViewPlugin-Version1.5(Oct20,2010)]]
=== Version 1.5 (Oct 20, 2010)

* Update to work with Hudson 1.381 or higher.
(https://issues.jenkins-ci.org/browse/JENKINS-7815[JENKINS-7815])
* Calculate view-health for a nested view by recursing into its
subviews.
(https://issues.jenkins-ci.org/browse/JENKINS-7125[JENKINS-7125])
* Export nested view details via Remote API.
(https://issues.jenkins-ci.org/browse/JENKINS-7489[JENKINS-7489])
* Don't allow setting a default subview for a nested view that is the
Hudson default view, as this prevents access to other top level view
tabs. (https://issues.jenkins-ci.org/browse/JENKINS-7362[JENKINS-7362])

[[NestedViewPlugin-Version1.4(Jul12,2010)]]
=== Version 1.4 (Jul 12, 2010)

* Update to work with Hudson 1.366 or higher.

[[NestedViewPlugin-Version1.3(Jun16,2010)]]
=== Version 1.3 (Jun 16, 2010)

* Sort subviews alphabetically.
(https://issues.jenkins-ci.org/browse/JENKINS-6757[JENKINS-6757])
* Russian translation.

[[NestedViewPlugin-Version1.2(May27,2010)]]
=== Version 1.2 (May 27, 2010)

* Add weather icons in nested view.
(https://issues.jenkins-ci.org/browse/JENKINS-6235[JENKINS-6235])

[[NestedViewPlugin-Version1.1(Mar22,2010)]]
=== Version 1.1 (Mar 22, 2010)

* Spanish translation.

[[NestedViewPlugin-Version1.0(Jan21,2010)]]
=== Version 1.0 (Jan 21, 2010)

* Initial release.
