Enhances Pipeline plugin to handle branches better by automatically
grouping builds from different branches.

Automatically creates a new Jenkins job whenever a new branch is pushed
to a source code repository. +
Other plugins can define various branch types, e.g. a Git branch, a
Subversion branch, a GitHub Pull Request etc.

See this blog post for more
info:https://jenkins.io/blog/2015/12/03/pipeline-as-code-with-multibranch-workflows-in-jenkins/

A component of the
https://wiki.jenkins.io/display/JENKINS/Pipeline+Plugin[Pipeline
Plugin].

[[PipelineMultibranchPlugin-Notes]]
== Notes

To determine the branch being built - use the environment variable
`+BRANCH_NAME+` - e.g. `+${env.BRANCH_NAME+`}

[[PipelineMultibranchPlugin-Changelog]]
== Changelog

[[PipelineMultibranchPlugin-2.21(Mar7,2019)]]
=== 2.21 (Mar 7, 2019)

* [.jira-issue .conf-macro .output-block]#
https://issues.jenkins-ci.org/browse/JENKINS-43194[[.aui-icon .aui-icon-wait .issue-placeholder]##
##JENKINS-43194] - [.summary]#Getting issue details...#
[.aui-lozenge .aui-lozenge-subtle .aui-lozenge-default .issue-placeholder]#STATUS#
#  Make SCMBinder try to abort builds in which Jenkinsfile has been
modified by an untrusted contributor
(https://github.com/jenkinsci/workflow-multibranch-plugin/pull/69[PR
#69])
* Migrate Chinese localization to another plugin
(https://github.com/jenkinsci/workflow-multibranch-plugin/pull/80[PR
#80])
* [.jira-issue .conf-macro .output-block]#
https://issues.jenkins-ci.org/browse/JENKINS-55116[[.aui-icon .aui-icon-wait .issue-placeholder]##
##JENKINS-55116] - [.summary]#Getting issue details...#
[.aui-lozenge .aui-lozenge-subtle .aui-lozenge-default .issue-placeholder]#STATUS#
#  Workaround Hack patch fix to allow at least a rescan to work when it
happens
(https://github.com/jenkinsci/workflow-multibranch-plugin/pull/83[PR
#83])
* [.jira-issue .conf-macro .output-block]#
https://issues.jenkins-ci.org/browse/JENKINS-2111[[.aui-icon .aui-icon-wait .issue-placeholder]##
##JENKINS-2111] - [.summary]#Getting issue details...#
[.aui-lozenge .aui-lozenge-subtle .aui-lozenge-default .issue-placeholder]#STATUS#
#  Integration test of new workspace naming strategy
(https://github.com/jenkinsci/workflow-multibranch-plugin/pull/82[PR
#82])
* Add gitDirectory symbol to GitDirectorySCMNavigator
(https://github.com/jenkinsci/workflow-multibranch-plugin/pull/79[PR
#79])

[[PipelineMultibranchPlugin-2.20(July9,2018)]]
=== 2.20 (July 9, 2018)

* Test fixes.

[[PipelineMultibranchPlugin-2.19(May17,2018)]]
=== 2.19 (May 17, 2018)

* Bugfix: builds failing upon running a JobPropertyStep with error "did
not yet start" if previous build was hard-killed or failed before
Pipeline began running
(https://issues.jenkins-ci.org/browse/JENKINS-51290[JENKINS-51290])

[[PipelineMultibranchPlugin-2.18(Apr20,2018)]]
=== 2.18 (Apr 20, 2018)

* Correct small bug from the improper use of the
FlowExecutionOwner.getOrNull() call for getting the previous Properties
for a step (visible as a result of
https://issues.jenkins-ci.org/browse/JENKINS-50784[JENKINS-50784])

[[PipelineMultibranchPlugin-2.17(Jan22,2018)]]
=== 2.17 (Jan 22, 2018)

* Provide a BranchProperty to support setting configuring durability
per-branch (supports
https://issues.jenkins-ci.org/browse/JENKINS-47300[JENKINS-47300])
* Massive updates to dependencies and tests
* Bugfix: https://issues.jenkins-ci.org/browse/JENKINS-42817[JENKINS-42817]
readTrusted Pipeline from SCM only works in */master

[[PipelineMultibranchPlugin-2.16(Jun19,2017)]]
=== 2.16 (Jun 19, 2017)

* Bugfix: Stop removing JobProperties defined outside a step
(https://issues.jenkins-ci.org/browse/JENKINS-44848[JENKINS-44848])

[[PipelineMultibranchPlugin-2.15(Jun01,2017)]]
=== 2.15 (Jun 01, 2017)

* https://issues.jenkins-ci.org/browse/JENKINS-34561[JENKINS-34561] Option
to select a script name/path other than `+Jenkinsfile+`.

[[PipelineMultibranchPlugin-2.14(Mar10,2017)]]
=== 2.14 (Mar 10, 2017)

* https://issues.jenkins-ci.org/browse/JENKINS-40558[JENKINS-40558] Replace
in-line help references of "pipeline script" with "pipeline" to clarify
that https://wiki.jenkins.io/display/JENKINS/Pipeline+Model+Definition+Plugin[Pipeline
Model Definition Plugin] works with multibranch

[[PipelineMultibranchPlugin-2.13(Mar03,2017)]]
=== 2.13 (Mar 03, 2017)

* https://issues.jenkins-ci.org/browse/JENKINS-33273[JENKINS-33273] Load
`+Jenkinsfile+` (or any file requested in `+loadTrusted+`) directly from
the SCM rather than doing a checkout. Requires a compatible SCM
(currently Git or GitHub).
* https://issues.jenkins-ci.org/browse/JENKINS-40521[JENKINS-40521]
Orphaned branch projects are now effectively disabled.
* https://issues.jenkins-ci.org/browse/JENKINS-41146[JENKINS-41146] Help
text improvement.
* API change: `+AbstractWorkflowMultiBranchProjectFactory+` implementers
may now throw `+IOException+`.

[.aui-icon .aui-icon-small .aui-iconfont-info .confluence-information-macro-icon]#
#

One aspect of
https://issues.jenkins-ci.org/browse/JENKINS-33273[JENKINS-33273] is
that you will not get an SCM changelog from a lightweight checkout of
`+Jenkinsfile+` itself---only if your script actually runs
`+checkout scm+`.

This behavior change can be suppressed in case of emergency using
`+-Dorg.jenkinsci.plugins.workflow.multibranch.SCMBinder.USE_HEAVYWEIGHT_CHECKOUT=true+`.

[[PipelineMultibranchPlugin-2.12(Feb02,2017)]]
=== 2.12 (Feb 02, 2017)

* https://issues.jenkins-ci.org/browse/JENKINS-40906[JENKINS-40906] Add
missing help text and configuration UI

[[PipelineMultibranchPlugin-2.10(Jan16,2017)]]
=== 2.10 (Jan 16, 2017)

* image:docs/images/warning.svg[(warning)]
  Please read https://jenkins.io/blog/2017/01/17/scm-api-2/[this Blog
Post] before upgrading
* https://issues.jenkins-ci.org/browse/JENKINS-40906[JENKINS-40906] Resolve
an SCM from an SCMSource and a list of candidate target branch names
* https://issues.jenkins-ci.org/browse/JENKINS-39355[JENKINS-39355] Use
SCM API 2.0.x APIs
* https://issues.jenkins-ci.org/browse/JENKINS-32179[JENKINS-32179] Branch
indexing always attempts to create a new project for conflicting branch
names from multiple sources
* Added subversion based integration tests
* If SCMSource.fetch returns null abort the build.
* https://issues.jenkins-ci.org/browse/JENKINS-35698[JENKINS-35698] Initial
run of parameterized pipeline build should return properties default
value
* https://issues.jenkins-ci.org/browse/JENKINS-38987[JENKINS-38987] SCMHead/SCMSource/SCMNavigator
need getPronoun() to assist contextual naming
* https://issues.jenkins-ci.org/browse/JENKINS-38960[JENKINS-38960] Deprecate
TopLevelItemDescriptor.getIconFilePathPattern() and
TopLevelItemDescriptor.getIconFile(String)

[[PipelineMultibranchPlugin-2.10-beta-1(Dec16,2016)]]
=== 2.10-beta-1 (Dec 16, 2016)

* Updated to use new multibranch-related APIs.
* More robust handling of invalid revisions.

[[PipelineMultibranchPlugin-2.9.2(Nov09,2016)]]
=== 2.9.2 (Nov 09, 2016)

* 2.9.1 was corrupt.

[[PipelineMultibranchPlugin-2.9.1(Nov09,2016)]]
=== 2.9.1 (Nov 09, 2016)

* In cases where the SCM source does not recognize a branch and fails to
determine its tip revision, fail with a clearer message.

[.aui-icon .aui-icon-small .aui-iconfont-error .confluence-information-macro-icon]#
#

Do not use. Use 2.9.2 instead.

[[PipelineMultibranchPlugin-2.9(Sep23,2016)]]
=== 2.9 (Sep 23, 2016)

* https://issues.jenkins-ci.org/browse/JENKINS-37005[JENKINS-37005] Warn
about use of the `+properties+` step from a non-multibranch project.
* https://issues.jenkins-ci.org/browse/JENKINS-37538[JENKINS-37538]
Ensuring that `+readTrusted+` output is displayed incrementally, and can
be interrupted.

[[PipelineMultibranchPlugin-2.8(Jun15,2016)]]
=== 2.8 (Jun 15, 2016)

* https://issues.jenkins-ci.org/browse/JENKINS-31386[JENKINS-31386] +
https://issues.jenkins-ci.org/browse/JENKINS-34596[JENKINS-34596]: allow
use of `+readTrusted+` inside a single-branch _Pipeline Script from
SCM_.

[[PipelineMultibranchPlugin-2.7(Jun09,2016)]]
=== 2.7 (Jun 09, 2016)

* https://issues.jenkins-ci.org/browse/JENKINS-34246[JENKINS-34246]
Integration of upstream fix to orphan or modify multibranch projects
inside an organization folder as project recognizers dictate.

[[PipelineMultibranchPlugin-2.6(Jun02,2016)]]
=== 2.6 (Jun 02, 2016)

* https://issues.jenkins-ci.org/browse/JENKINS-34596[JENKINS-34596]
Added `+readTrusted+` step to provide greater flexibility when building
untrusted pull requests.
* Internal refactoring to expose multibranch functionality to other
plugins.

[[PipelineMultibranchPlugin-2.5(Jun01,2016)]]
=== 2.5 (Jun 01, 2016)

* https://issues.jenkins-ci.org/browse/JENKINS-32396[JENKINS-32396] Pick
up dependency with new feature to suppress automatic triggers of certain
branch projects.
* https://issues.jenkins-ci.org/browse/JENKINS-30206[JENKINS-30206]
Failure to update branch projects with modified configuration (only
affecting newly introduced trigger suppression property).

[[PipelineMultibranchPlugin-2.4(May23,2016)]]
=== 2.4 (May 23, 2016)

* https://issues.jenkins-ci.org/browse/JENKINS-31831[JENKINS-31831] Make
new _Pipeline Syntax_ link appear on multibranch Pipeline projects, and
organization folders configured with the Pipeline factory.

[[PipelineMultibranchPlugin-2.3(Apr14,2016)]]
=== 2.3 (Apr 14, 2016)

* https://issues.jenkins-ci.org/browse/JENKINS-34235[JENKINS-34235]
Pipeline Multibranch project icon not found in the New Item page.

[[PipelineMultibranchPlugin-2.2(Apr14,2016)]]
=== 2.2 (Apr 14, 2016)

* *Wrong release*.

[[PipelineMultibranchPlugin-2.1(Apr13,2016)]]
=== 2.1 (Apr 13, 2016)

* https://issues.jenkins-ci.org/browse/JENKINS-31162[JENKINS-31162]
Support for Item categorization.

[[PipelineMultibranchPlugin-2.0(Apr05,2016)]]
=== 2.0 (Apr 05, 2016)

* First release under per-plugin versioning scheme. See
https://github.com/jenkinsci/workflow-plugin/blob/82e7defa37c05c5f004f1ba01c93df61ea7868a5/CHANGES.md[1.x
changelog] for earlier releases.
