Allows credentials to be bound to environment variables for use from
miscellaneous build steps.[.conf-macro .output-inline]##

[cols="",options="header",]
|===
|Plugin Information
|View Credentials Binding
https://plugins.jenkins.io/credentials-binding[on the plugin site] for
more information.
|===

[.aui-icon .aui-icon-small .aui-iconfont-info .confluence-information-macro-icon]##

Older versions of this plugin may not be safe to use. Please review the
following warnings before using an older version:

* https://jenkins.io/security/advisory/2018-02-05/[Improper masking of
secrets in rare circumstances]

You may have a keystore for jarsigner, a list of passwords, or other
confidential files or strings which you want to be used by a job but
which should not be kept in its SCM, or even visible from its
config.xml. Saving these files on the server and referring to them by
absolute path requires you to have a server login, and does not work on
slaves. This plugin gives you an easy way to package up all a job’s
secret files and passwords and access them using a single environment
variable during the build.

To use, first go to the Credentials link and add items of type _Secret
file_ and/or _Secret text_. Now in a freestyle job, check the box _Use
secret text(s) or file(s)_ and add some variable bindings which will use
your credentials. The resulting environment variables can be accessed
from shell script build steps and so on. (You probably want to start any
shell script with `+set +x+`, or batch script with `+@echo off+`.
https://issues.jenkins-ci.org/browse/JENKINS-14731[JENKINS-14731]).

For more details of how this works, check the
https://cloudbees.zendesk.com/hc/en-us/articles/203802500-Injecting-Secrets-into-Jenkins-Build-Jobs[Injecting
Secrets into Jenkins Build Jobs] article at CloudBees.

From a Pipeline job, define your credentials, then check _Snippet
Generator_ for a syntax example of the `+withCredentials+` step. Any
secrets in the build log will be masked automatically.

A typical example of a username password type credential (example from
here) would look like: 

[source,syntaxhighlighter-pre]
----
withCredentials([usernamePassword(credentialsId: 'amazon', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
  // available as an env variable, but will be masked if you try to print it out any which way
  // note: single quotes prevent Groovy interpolation; expansion is by Bourne Shell, which is what you want
  sh 'echo $PASSWORD'
  // also available as a Groovy variable
  echo USERNAME
  // or inside double quotes for string interpolation
  echo "username is $USERNAME"
}
----

[[CredentialsBindingPlugin-Changelog]]
== Changelog

[[CredentialsBindingPlugin-Version1.19(2019-05-31)]]
=== Version 1.19 (2019-05-31)

* [.jira-issue .conf-macro .output-block]#
https://issues.jenkins-ci.org/browse/JENKINS-42950[[.aui-icon .aui-icon-wait .issue-placeholder]##
##JENKINS-42950] - [.summary]#Getting issue details...#
[.aui-lozenge .aui-lozenge-subtle .aui-lozenge-default .issue-placeholder]#STATUS#
#  Expanded secret masking to include some variants commonly produced by
shells when metacharacters are involved.

[[CredentialsBindingPlugin-Version1.18(2019-02-25)]]
=== Version 1.18 (2019-02-25)

* [.jira-issue .conf-macro .output-block]#
https://issues.jenkins-ci.org/browse/JENKINS-42950[[.aui-icon .aui-icon-wait .issue-placeholder]##
##JENKINS-42950] - [.summary]#Getting issue details...#
[.aui-lozenge .aui-lozenge-subtle .aui-lozenge-default .issue-placeholder]#STATUS#
#  Better documentation about limitations and best practices.
* [.jira-issue .conf-macro .output-block]#
https://issues.jenkins-ci.org/browse/JENKINS-49337[[.aui-icon .aui-icon-wait .issue-placeholder]##
##JENKINS-49337] - [.summary]#Getting issue details...#
[.aui-lozenge .aui-lozenge-subtle .aui-lozenge-default .issue-placeholder]#STATUS#
#  Avoiding blocking the Pipeline interpreter during block cleanup even
if Remoting hangs.
* Avoid printing a stack trace when a `+credentialsId+`  is not found.

[[CredentialsBindingPlugin-Version1.17(2018-10-29)]]
=== Version 1.17 (2018-10-29)

* Improved stream flush behavior in light
of https://jenkins.io/jep/210[JEP-210].

[[CredentialsBindingPlugin-Version1.16(Mar19,2018)]]
=== Version 1.16 (Mar 19, 2018)

* [.jira-issue .conf-macro .output-block]#
https://issues.jenkins-ci.org/browse/JENKINS-49535[[.aui-icon .aui-icon-wait .issue-placeholder]##
##JENKINS-49535] - [.summary]#Getting issue details...#
[.aui-lozenge .aui-lozenge-subtle .aui-lozenge-default .issue-placeholder]#STATUS#
#
* Improving help text in light of 
[.jira-issue .conf-macro .output-block]#
https://issues.jenkins-ci.org/browse/JENKINS-50242[[.aui-icon .aui-icon-wait .issue-placeholder]##
##JENKINS-50242] - [.summary]#Getting issue details...#
[.aui-lozenge .aui-lozenge-subtle .aui-lozenge-default .issue-placeholder]#STATUS#
# .

[[CredentialsBindingPlugin-Version1.15(Feb05,2018)]]
=== Version 1.15 (Feb 05, 2018)

* https://jenkins.io/security/advisory/2018-02-05/[Fix security issue]

[[CredentialsBindingPlugin-Version1.14(Jan17,2018)]]
=== Version 1.14 (Jan 17, 2018)

* [.jira-issue .conf-macro .output-block]#
https://issues.jenkins-ci.org/browse/JENKINS-37871[[.aui-icon .aui-icon-wait .issue-placeholder]##
##JENKINS-37871] - [.summary]#Getting issue details...#
[.aui-lozenge .aui-lozenge-subtle .aui-lozenge-default .issue-placeholder]#STATUS#
#  Adjusted order of freestyle build wrapper relative to other wrappers.
* [.jira-issue .conf-macro .output-block]#
https://issues.jenkins-ci.org/browse/JENKINS-48118[[.aui-icon .aui-icon-wait .issue-placeholder]##
##JENKINS-48118] - [.summary]#Getting issue details...#
[.aui-lozenge .aui-lozenge-subtle .aui-lozenge-default .issue-placeholder]#STATUS#
#  Metadata fixes useful for `+plugin-compat-tester+`.

[[CredentialsBindingPlugin-Version1.13(Aug08,2017)]]
=== Version 1.13 (Aug 08, 2017)

* https://issues.jenkins-ci.org/browse/JENKINS-28399[JENKINS-28399] Binding
type for SSH user private key credentials.
* https://issues.jenkins-ci.org/browse/JENKINS-41760[JENKINS-41760] Corrupted
output when no credentials were specified, or a supposed secret was in
fact blank.
* https://issues.jenkins-ci.org/browse/JENKINS-43199[JENKINS-43199] File
descriptor leak when using build wrapper.

[[CredentialsBindingPlugin-Version1.12(Jun15,2017)]]
=== Version 1.12 (Jun 15, 2017)

* Binding type for certificate credentials.
* New APIs `+AbstractOnDiskBinding+` and `+UnbindableDir+`.

[[CredentialsBindingPlugin-Version1.11(Mar30,2017)]]
=== Version 1.11 (Mar 30, 2017)

* https://issues.jenkins-ci.org/browse/JENKINS-42999[JENKINS-42999]
Allow non-file-based credentials to be used from `+withCredentials+`
outside a `+node+` block.
* Japanese localization.

[[CredentialsBindingPlugin-Version1.10(Nov07,2016)]]
=== Version 1.10 (Nov 07, 2016)

* https://issues.jenkins-ci.org/browse/JENKINS-24805[JENKINS-24805] Mask
passwords in freestyle builds, not just in Pipeline builds.
* Masking did not work correctly if some secrets were a substring of
others.
* https://issues.jenkins-ci.org/browse/JENKINS-38831[JENKINS-38831]
Track credentials usage.
* Adding symbols to binding types for better readability in Pipeline
(and probably also Job DSL).

[[CredentialsBindingPlugin-Version1.9(Aug19,2016)]]
=== Version 1.9 (Aug 19, 2016)

* https://issues.jenkins-ci.org/browse/JENKINS-37541[JENKINS-37541] prevent
NPE while reading back SecretBuildWrapper
* Migrate to new parent pom 

[[CredentialsBindingPlugin-Version1.8(Jun10,2016)]]
=== Version 1.8 (Jun 10, 2016)

* https://issues.jenkins-ci.org/browse/JENKINS-35490[JENKINS-35490] fix
regression introduced in JENKINS-27387 fix
* https://issues.jenkins-ci.org/browse/JENKINS-35095[JENKINS-35095] migrate
to new parent pom 

[[CredentialsBindingPlugin-Version1.7(Mar03,2016)]]
=== Version 1.7 (Mar 03, 2016)

* https://issues.jenkins-ci.org/browse/JENKINS-32943[JENKINS-32943]/https://issues.jenkins-ci.org/browse/JENKINS-27152[JENKINS-27152]
Use a standardized temporary directory understood by Docker Pipeline.
* https://issues.jenkins-ci.org/browse/JENKINS-27387[JENKINS-27387]
Failure to generate snippet in a Pipeline configuration page.

[[CredentialsBindingPlugin-Version1.6(Oct16,2015)]]
=== Version 1.6 (Oct 16, 2015)

* https://issues.jenkins-ci.org/browse/JENKINS-30941[JENKINS-30941]
Fixed regression in 1.5 affecting ZIP file bindings.
* Resource leak potentially affecting ZIP file bindings.
* https://issues.jenkins-ci.org/browse/JENKINS-30326[JENKINS-30326]
updated dependency on credentials plugin to 1.23

[[CredentialsBindingPlugin-Version1.5(Aug06,2015)]]
=== Version 1.5 (Aug 06, 2015)

* https://issues.jenkins-ci.org/browse/JENKINS-29255[JENKINS-29255] Set
restrictive file permission on _Secret File_ binding, to make it easier
to use an SSH private key this way.

[[CredentialsBindingPlugin-Version1.4(Apr01,2015)]]
=== Version 1.4 (Apr 01, 2015)

* Updated to Jenkins 1.596.1 and Workflow 1.5.
* https://issues.jenkins-ci.org/browse/JENKINS-27486[JENKINS-27486]
`+withCredentials+` step should mask any passwords accidentally printed
to the log.
* https://issues.jenkins-ci.org/browse/JENKINS-27631[JENKINS-27631]
`+withCredentials+` step should not store passwords even temporarily in
`+program.dat+` in the build directory.
* https://issues.jenkins-ci.org/browse/JENKINS-27389[JENKINS-27389]
`+withCredentials+` step was exposing variables to external processes
but not to Groovy code using `+env.PASSWORD+` syntax.
* Improved help for `+withCredentials+`.
* Improved error diagnostics for `+withCredentials+`.

[[CredentialsBindingPlugin-Version1.3(Jan20,2015)]]
=== Version 1.3 (Jan 20, 2015)

* https://issues.jenkins-ci.org/browse/JENKINS-26051[JENKINS-26051]
Added `+withCredentials+` Workflow step.
http://developer-blog.cloudbees.com/2015/01/workflow-integration-for-credentials.html[Blog]
* https://issues.jenkins-ci.org/browse/JENKINS-23468[JENKINS-23468]
Allowed username & password to be bound to separate variables.
* SPI changes to permit the above two features.

[[CredentialsBindingPlugin-Version1.2(Oct07,2014)]]
=== Version 1.2 (Oct 07, 2014)

* SECURITY-158 fix.

[[CredentialsBindingPlugin-Version1.1(Aug11,2014)]]
=== Version 1.1 (Aug 11, 2014)

* Add support for parameterized credentials (from credentials plugin
1.16.1)

[[CredentialsBindingPlugin-Version1.0(Jun16,2014)]]
=== Version 1.0 (Jun 16, 2014)

First general release.

* Supporting username/password credentials.
* Marking added environment variables as “sensitive”, so other code
showing them should display the values masked.

[[CredentialsBindingPlugin-Version1.0beta1(Oct01,2013)]]
=== Version 1.0 beta 1 (Oct 01, 2013)

* Factored out from
https://wiki.jenkins.io/display/JENKINS/Plain+Credentials+Plugin[Plain
Credentials Plugin].
