[.conf-macro .output-inline]#This plugin allows to automatically
generate http://allure.qatools.ru/[Allure Report] and attach it to build
during Jenkins job run.#

Plugin builds are located
here: https://ci.qameta.io/job/allure-plugin/[https://ci.qameta.io/job/allure-plugin]

[[AllurePlugin-Usage]]
== *Usage*

Read more
at http://wiki.qatools.ru/display/AL/Allure+Jenkins+Plugin[plugin
documentation page]

[[AllurePlugin-Changelog]]
== *Changelog*

*Version 2.26.0 (Jan, 22, 2018)*

Improvements

* Add classes to security whitelist
(fixes https://github.com/jenkinsci/allure-plugin/issues/192[#192],
via https://github.com/jenkinsci/allure-plugin/pull/195[#195])
* Add pipeline trend
(fixes https://github.com/jenkinsci/allure-plugin/issues/174[#174],
via https://github.com/jenkinsci/allure-plugin/pull/191[#191])

Fixes

* Fix matrix job report generation
(fixes https://github.com/jenkinsci/allure-plugin/issues/190[#190],
via https://github.com/jenkinsci/allure-plugin/pull/191[#191])

Links

https://github.com/jenkinsci/allure-plugin/compare/2.25.1...2.26.0[Commits
since 2.25.1]

 

*Version 2.25.1 (Dec, 18, 2017)* 

Improvements

* Update dependencies
(via https://github.com/jenkinsci/allure-plugin/pull/177[#177])
- https://wiki.jenkins-ci.org/display/JENKINS/Allure+Plugin[@eroshenkoam]

Fixes

* Fix filepath serialization problem
(via https://github.com/jenkinsci/allure-plugin/pull/188[#188])
- https://wiki.jenkins-ci.org/display/JENKINS/Allure+Plugin[@vbragin]
* Fix NPE in build summary
(fixes https://github.com/jenkinsci/allure-plugin/issues/172[#172],
via https://github.com/jenkinsci/allure-plugin/pull/179[#179])
- https://wiki.jenkins-ci.org/display/JENKINS/Allure+Plugin[@vbragin]

Links

https://github.com/jenkinsci/allure-plugin/compare/2.25...2.25.1[Commits
since 2.25]

 

*Version 2.25 (Nov, 01, 2017)*

New Features

* Add allure report property
(fixes https://github.com/jenkinsci/allure-plugin/issues/106[#106],
fixes https://github.com/jenkinsci/allure-plugin/issues/164[#164],
via https://github.com/jenkinsci/allure-plugin/pull/170[#170])

Links

https://github.com/jenkinsci/allure-plugin/compare/2.24...2.25[Commits
since 2.24]

 

*Version 2.24 (Oct, 11, 2017)*

 

New Features

* Add 'disable allure report' property
(fixes https://github.com/jenkinsci/allure-plugin/issues/92[#92],
via https://github.com/jenkinsci/allure-plugin/pull/165[#165])
- https://wiki.jenkins-ci.org/display/JENKINS/Allure+Plugin[@vbragin]

Improvements

* Add build results base on tests
(fixes https://github.com/jenkinsci/allure-plugin/issues/13[#13],
via https://github.com/jenkinsci/allure-plugin/pull/167[#167])
- https://wiki.jenkins-ci.org/display/JENKINS/Allure+Plugin[@vbragin]
* Add properties wrapping
(fixes https://github.com/jenkinsci/allure-plugin/issues/162[#162],
fixes https://github.com/jenkinsci/allure-plugin/issues/146[#146],
via https://github.com/jenkinsci/allure-plugin/pull/166[#166])
- https://wiki.jenkins-ci.org/display/JENKINS/Allure+Plugin[@vbragin]

Links

https://github.com/jenkinsci/allure-plugin/compare/2.23...2.24[Commits
since 2.23]

 

*Version 2.23 (Sep, 11, 2017) * 

 +

Improvements

* Downgrade jenkins core version to 1.642.4
(via https://github.com/jenkinsci/allure-plugin/pull/160[#160])
- https://wiki.jenkins-ci.org/display/JENKINS/Allure+Plugin[@eroshenkoam]

Links

https://github.com/jenkinsci/allure-plugin/compare/2.22...2.23[Commits
since 2.22]

 

*Version 2.22 (Aug, 03, 2017)* 

Fixes

* Fix npe in build action
(fixes https://github.com/jenkinsci/allure-plugin/issues/152[#152],
fixes https://github.com/jenkinsci/allure-plugin/issues/153[#153],
via https://github.com/jenkinsci/allure-plugin/pull/154[#154])
- https://wiki.jenkins-ci.org/display/JENKINS/Allure+Plugin[@eroshenkoam]

Links

https://github.com/jenkinsci/allure-plugin/compare/2.21...2.22[Commits
since 2.21]

 

*Version 2.21 (Aug, 02, 2017) *

Fixes

* Fix duplicates
(fixes https://github.com/jenkinsci/allure-plugin/issues/115[#115],
via https://github.com/jenkinsci/allure-plugin/pull/149[#149])
- https://wiki.jenkins-ci.org/display/JENKINS/Allure+Plugin[@eroshenkoam]
* Fix npe with build summary (fixes 147,
via https://github.com/jenkinsci/allure-plugin/pull/150[#150])
- https://wiki.jenkins-ci.org/display/JENKINS/Allure+Plugin[@eroshenkoam]

Links

https://github.com/jenkinsci/allure-plugin/compare/2.20...2.21[Commits
since 2.20]

 

**Version 2.20 (Jul, 16, 2017)**

 New features

* global properties
(fixes https://github.com/jenkinsci/allure-plugin/issues/132[#132],
via https://github.com/jenkinsci/allure-plugin/pull/143[#143])
- https://wiki.jenkins-ci.org/display/JENKINS/Allure+Plugin[@eroshenkoam]
* add graph trend
(fixes https://github.com/jenkinsci/allure-plugin/issues/46[#46],
via https://github.com/jenkinsci/allure-plugin/pull/140[#140])
- https://wiki.jenkins-ci.org/display/JENKINS/Allure+Plugin[@ehborisov]

Improvements

* update executor json
(fixes https://github.com/jenkinsci/allure-plugin/issues/137[#137],
via https://github.com/jenkinsci/allure-plugin/pull/138[#138])
- https://wiki.jenkins-ci.org/display/JENKINS/Allure+Plugin[@ehborisov]

Fixes

* fix properties npe
(fixes https://github.com/jenkinsci/allure-plugin/issues/125[#125],
via https://github.com/jenkinsci/allure-plugin/pull/142[#142])
- https://wiki.jenkins-ci.org/display/JENKINS/Allure+Plugin[@eroshenkoam]

Links

https://github.com/jenkinsci/allure-plugin/compare/2.19...2.20[Commits
since 2.19]

*Version 2.19 (Jul, 01, 2017)*

Incompatibility

* pipeline syntax changed from
+
....
allure([results: [[path: 'allure-results']]])
....
+
to more simple
+
....
allure results: [[path: 'allure-results']]
....

Improvements

* support glob syntax
(via https://github.com/jenkinsci/allure-plugin/pull/134[#134])
- https://wiki.jenkins-ci.org/display/JENKINS/Allure+Plugin[@eroshenkoam]
* build id to executor info
(via https://github.com/jenkinsci/allure-plugin/pull/130[#130])
- https://wiki.jenkins-ci.org/display/JENKINS/Allure+Plugin[@ehborisov]
* use data bound setters
(via https://github.com/jenkinsci/allure-plugin/pull/131[#131])
- https://wiki.jenkins-ci.org/display/JENKINS/Allure+Plugin[@ehborisov]

Fixes

* disable cache
(fixes https://github.com/jenkinsci/allure-plugin/issues/113[#113],
via https://github.com/jenkinsci/allure-plugin/pull/135[#135])
- https://wiki.jenkins-ci.org/display/JENKINS/Allure+Plugin[@eroshenkoam]
* fix declarative pipeline
(via https://github.com/jenkinsci/allure-plugin/pull/133[#133])
- https://wiki.jenkins-ci.org/display/JENKINS/Allure+Plugin[@ehborisov]

Links

https://github.com/jenkinsci/allure-plugin/compare/2.18...2.19[Commits
since 2.18]

* +
*

*Version 2.18 (Jun, 03, 2017)*

 Fixes:

* fix null config parameters
(https://github.com/jenkinsci/allure-plugin/issues/125[#125])
- https://wiki.jenkins-ci.org/display/JENKINS/Allure+Plugin[@eroshenkoam]

Improvements:

* variables in results path
(https://github.com/jenkinsci/allure-plugin/issues/107[#107])
- https://wiki.jenkins-ci.org/display/JENKINS/Allure+Plugin[@eroshenkoam]
* variables in properties
(https://github.com/jenkinsci/allure-plugin/issues/55[#55])
- https://wiki.jenkins-ci.org/display/JENKINS/Allure+Plugin[@eroshenkoam]

Links

https://github.com/jenkinsci/allure-plugin/compare/2.17...2.18[Commits
since 2.17]

* +
*

*Version 2.17 (May, 31, 2017)*

Fixes:

* release version without snapshot
(https://github.com/jenkinsci/allure-plugin/issues/121[#121])
- https://wiki.jenkins-ci.org/display/JENKINS/Allure+Plugin[@eroshenkoam]

Improvements:

* allure 2 distribution path
- https://wiki.jenkins-ci.org/display/JENKINS/Allure+Plugin[@ehborisov]

Links

https://github.com/jenkinsci/allure-plugin/compare/2.16...2.17[Commits
since 2.16]

* +
*

*Version 2.16 (May, 29, 2017)* 

Fixes:

* wait for artifact uploading
(https://github.com/jenkinsci/allure-plugin/issues/73[#73])
- https://wiki.jenkins-ci.org/display/JENKINS/Allure+Plugin[@ehborisov]
* allure home setting
(https://github.com/jenkinsci/allure-plugin/issues/82[#82], https://github.com/jenkinsci/allure-plugin/issues/108[#108])
- https://wiki.jenkins-ci.org/display/JENKINS/Allure+Plugin[@ehborisov]
* allure properties setting
- https://wiki.jenkins-ci.org/display/JENKINS/Allure+Plugin[@ehborisov]

Improvements:

* switch to gradle
- https://wiki.jenkins-ci.org/display/JENKINS/Allure+Plugin[@ehborisov]
* migrate to jenkins pipeline
- https://wiki.jenkins-ci.org/display/JENKINS/Allure+Plugin[@eroshenkoam]

Links

https://github.com/jenkinsci/allure-plugin/compare/allure-jenkins-plugin-2.15...2.16[Commits
since 2.15]

 

*Version 2.15 (April 13, 2017)*

* https://github.com/jenkinsci/allure-plugin/issues/90[#90] fix npe when
open absence file
* https://github.com/jenkinsci/allure-plugin/issues/88[#88] fix pipeline
cli installation
* https://github.com/jenkinsci/allure-plugin/issues/93[#93] fix package
name mistake
* https://github.com/jenkinsci/allure-plugin/issues/95[#95] support
target path that type is soft link

Improvements:

* copy history directory [beta7]

[[AllurePlugin-GithubRelease]]
=== *https://github.com/jenkinsci/allure-plugin/releases/tag/allure-jenkins-plugin-2.15[Github Release]*

[[AllurePlugin-Version2.14(March23,2017)]]
=== *Version 2.14 (March 23, 2017)*

* fix zip error
* add allure home variable

https://github.com/jenkinsci/allure-plugin/releases/tag/allure-jenkins-plugin-2.14[Github
Release]

[[AllurePlugin-Version2.13(February12,2017)]]
=== *Version 2.13 (February 12, 2017)*

* fix backward capability with 2.10
* add issue template
* allure 2 support

https://github.com/jenkinsci/allure-plugin/releases/tag/allure-jenkins-plugin-2.13[Github
Release]

[[AllurePlugin-Version2.12(February8,2016)]]
=== *Version 2.12 (February 8, 2016)*

* Remove artifact manager factory

https://github.com/jenkinsci/allure-plugin/releases/tag/allure-jenkins-plugin-2.12[Github
Release]

[[AllurePlugin-Version2.11(January22,2016)]]
=== *Version 2.11 (January 22, 2016)*

Global refactoring

* Add more tests (an example, tests for matrix jobs)
* Fix sonar issues
* Fix findbugs issues
* Add history support
* Add executor support
* Change artifact coordinates
* Bump Jenkins version to 2.7
* Support pipeline
* Add pipeline tests
* Make sure that all Windows issues are fixed
* Add more tests for different Jenkins locations and results paths
(Windows escape issue)

https://github.com/jenkinsci/allure-plugin/releases/tag/allure-jenkins-plugin-2.11[Github
Release]

[[AllurePlugin-Version2.10(December2,2016)]]
=== *Version 2.10 (December 2, 2016)*

* Fix environment file creation problem

https://github.com/jenkinsci/allure-plugin/releases/tag/allure-jenkins-plugin-2.10[Github
Release]

[[AllurePlugin-Version2.9(November29,2016)]]
=== *Version 2.9 (November 29, 2016)*

* Global properties

https://github.com/jenkinsci/allure-plugin/releases/tag/allure-jenkins-plugin-2.9[Github
Release]

[[AllurePlugin-Version2.8(October30,2015).Globalrefactoring.Backwardcompatibilitymissing.]]
=== *Version 2.8 (October 30, 2015). Global refactoring. Backward compatibility missing.*

Backward Compatibility: 

* Use allure-commandline tool instead of maven. You need configure it
before use in Jenkins Global Configuration.
* Ant glob syntax not supported anymore. Use new line separated list of
results directories instead.
* Each job need to configure jdk to use. You can do it in job settings
or in plugin settings.

Read more
at http://wiki.qatools.ru/display/AL/Allure+Jenkins+Plugin[plugin
documentation page].

[[AllurePlugin-Version2.5(January29,2015)]]
=== Version 2.5 (January 29, 2015)

* Fix matrix report aggregation for dynamic slaves –
https://github.com/jenkinsci/allure-jenkins-plugin/issues/7[issue 7]
* Use jenkins proxy settings or own proxy settings to get remote
artifacts –
https://github.com/allure-framework/allure-jenkins-plugin/issues/32[issue
32]
* Various minor fixes

https://github.com/jenkinsci/allure-plugin/releases/tag/allure-jenkins-plugin-2.5[Github
Release]

[[AllurePlugin-Version2.3.2(October23,2014)]]
=== Version 2.3.2 (October 23, 2014)

* Fix global options being reset to defaults after restart –
https://github.com/allure-framework/allure-jenkins-plugin/issues/25[issue
25]
* Fix matrix job aggregation
- https://github.com/allure-framework/allure-jenkins-plugin/issues/23[Issue
23]
* Fix raise condition at creating internal dirs

https://github.com/jenkinsci/allure-plugin/releases/tag/allure-jenkins-plugin-2.3.2[Github
Release]

[[AllurePlugin-Version2.2(September15,2014)]]
=== Version 2.2 (September 15, 2014)

* add possibility to skip build env-vars from report
* rename LICENSE file
* fix docs

https://github.com/jenkinsci/allure-plugin/releases/tag/allure-jenkins-plugin-2.2[Github
Release]

[[AllurePlugin-Version2.1(August13,2014)]]
=== *Version 2.1 (August 13, 2014)*

* Jenkins matrix-job collector fails
* Remove by step synchronisation
* Badge link is relative and follow to 404 page when you in the
workspace

https://github.com/jenkinsci/allure-plugin/releases/tag/allure-jenkins-plugin-2.1[Github
Release]

[[AllurePlugin-Version2.0(August08,2014)]]
=== Version 2.0 (August 08, 2014)

* Add possibility to build any version of Allure Report for each job
* Add default global settings with overriding support
* Add build badge icon

https://github.com/jenkinsci/allure-plugin/releases/tag/allure-jenkins-plugin-2.0[Github
Release]

[[AllurePlugin-Version1.3(May28,2014)]]
=== Version 1.3 (May 28, 2014)

* Internal fixes

[[AllurePlugin-Version1.0(May23,2014)]]
=== Version 1.0 (May 23, 2014)

* Initial version
