https://wiki.jenkins-ci.org/display/JENKINS/Build+Keeper+Plugin#BuildKeeperPlugin-features[Features] +
https://wiki.jenkins-ci.org/display/JENKINS/Build+Keeper+Plugin#BuildKeeperPlugin-compatibility[Compatibility] +
https://wiki.jenkins-ci.org/display/JENKINS/Build+Keeper+Plugin#BuildKeeperPlugin-install[Install] +
https://wiki.jenkins-ci.org/display/JENKINS/Build+Keeper+Plugin#BuildKeeperPlugin-changelog[Change
log]

[#BuildKeeperPlugin-features .confluence-anchor-link .conf-macro .output-inline]#
#

[[BuildKeeperPlugin-Features]]
== Features

* Automatically mark builds as "keep forever" to prevent them from being
removed when using "discard old builds"
* Use the Policy extension point to define your own policies for
selecting builds to keep

[#BuildKeeperPlugin-compatibility .confluence-anchor-link .conf-macro .output-inline]#
#

[[BuildKeeperPlugin-Compatibility]]
== Compatibility

This plugin is compatible with Jenkins 1.408+

[#BuildKeeperPlugin-install .confluence-anchor-link .conf-macro .output-inline]#
#

[[BuildKeeperPlugin-Install]]
== Install

This plugin can be installed from the Plugin Manager (Manage Jenkins >
Manage Plugins) under "Build Wrappers".

To install manually, download the latest plugin from
http://mirrors.jenkins-ci.org/plugins/build-keeper-plugin/ and use the
Upload Plugin option in the Advanced tab of the Plugin Manager.

[#BuildKeeperPlugin-changelog .confluence-anchor-link .conf-macro .output-inline]#
#

[[BuildKeeperPlugin-Changelog]]
== Change log

[[BuildKeeperPlugin-1.3(16/04/2012)]]
=== 1.3 (16/04/2012)

* Add a policy that evaluates
https://wiki.jenkins-ci.org/display/JENKINS/Run+Condition+Plugin[Run
Conditions] and keeps the build if the build step would have run
* Now requires Jenkins 1.408 (from 1.396)

[[BuildKeeperPlugin-1.2(11/01/2012)]]
=== 1.2 (11/01/2012)

* Add a policy to keep the first failed build in a run of consecutive
failed builds

[[BuildKeeperPlugin-1.1(19/07/2011)]]
=== 1.1 (19/07/2011)

* Add "Keep the first successful build every x days" to keep at least
one build every so many days

[[BuildKeeperPlugin-1.0(18/07/2011)]]
=== 1.0 (18/07/2011)

* Initial release

Questions, Comments, Bugs and Feature Requests

[.aui-icon .aui-icon-small .aui-iconfont-info .confluence-information-macro-icon]#
#

Please post questions or comments about this plugin to the
http://jenkins-ci.org/content/mailing-lists[Jenkins User mailing
list]. +
To report a bug or request an enhancement to this plugin please
http://issues.jenkins-ci.org/browse/JENKINS/component/15894[create a
ticket in JIRA].
