[[AWSCodedeployplugin-AWSCodedeployplugin]]
== AWS Codedeploy plugin

[.conf-macro .output-inline]# #

[.aui-icon .aui-icon-small .aui-iconfont-info .confluence-information-macro-icon]##

Older versions of this plugin may not be safe to use. Please review the
following warnings before using an older version:

* https://jenkins.io/security/advisory/2018-06-25/#SECURITY-825[Serialization
of potentially sensitive build variables]
* https://jenkins.io/security/advisory/2018-06-25/#SECURITY-833[AWS
Secret Key stored in plain text]

The https://aws.amazon.com/codedeploy[AWS CodeDeploy] Jenkins plugin
provides a post-build step for your Jenkins project. Upon a successful
build, it will zip the workspace, upload to S3, and +
start a new deployment. Optionally, you can set it to wait for the
deployment to finish, making the final success contingent on the success
of the deployment.

[[AWSCodedeployplugin-Settingup]]
=== Setting up

After building and installing the plugin, some simple configuration is
needed for your project.

. Open up your project configuration
. In the *Post-build Actions* section, select *Deploy an application to
AWS CodeDeploy*
. Application Name, Deployment Group, Deployment Config, and region are
all required options.
. For authentication, there are two options. Either option requires that
the associated role has, at minimum, a policy that permits
`+codedeploy:*+` and `+s3:Put*+`.
.. Access/Secret key pair. For example, the keys associated with a
specific IAM user. If left blank, the default chain of credentials will
be checked.
.. Temporary access keys. These will use the global keys from the
Jenkins instance.

[[AWSCodedeployplugin-License]]
=== License

This plugin is licensed under Apache 2.0. See the
https://github.com/jenkinsci/aws-codedeploy-plugin/blob/master/LICENSE[LICENSE
file] in the source repository for more information.
