Eliminate running processes before or after
build.[.conf-macro .output-inline]##

[cols="",options="header",]
|===
|Plugin Information
|View Process cleaner https://plugins.jenkins.io/proc-cleaner-plugin[on
the plugin site] for more information.
|===

[.aui-icon .aui-icon-small .aui-iconfont-info .confluence-information-macro-icon]##

Older versions of this plugin may not be safe to use. Please review the
following warnings before using an older version:

* https://jenkins.io/security/advisory/2017-04-10/[Arbitrary code
execution vulnerability]

With this plugin user can decide to clean the processes either before or
after the build. It can either kill all processes started by the user
that runs Jenkins agent (except of that process) or all child processes
of Jenkins agent (note this will not affect processes running on
background).

Note the plugin can decide not to perform the cleanup in case there is a
chance it will affect other jobs on the same machine. In other words, it
will be skipped when there is another build running on the same slave.

 

[[ProcessCleanerPlugin-Changelog]]
== Changelog

[[ProcessCleanerPlugin-2.0]]
== 2.0

Renew the plugin distribution after
https://issues.jenkins-ci.org/browse/SECURITY-489[SECURITY-489.]

* The _[.blob-code-inner]#Groovy script [.x .x-first .x-last]#process
cleaner##_ is no longer supported by plugin.
** Upgrading from older version is safe in a sense the scripts are
preserved for users to migrate them to different solutions but *scripts
are no longer executed*.
