[.conf-macro .output-inline]# #

[.aui-icon .aui-icon-small .aui-iconfont-info .confluence-information-macro-icon]##

Older versions of this plugin may not be safe to use. Please review the
following warnings before using an older version:

* https://jenkins.io/security/advisory/2017-08-07/[Users with read
access could interact with input step by default]

Adds the Pipeline step ‘input’ to wait for human input or approval.

A component of
https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Plugin[Pipeline
Plugin].

[[PipelineInputStepPlugin-Changelog]]
== Changelog

[[PipelineInputStepPlugin-2.11(Aug27,2019)]]
=== 2.11 (Aug 27, 2019)

* https://issues.jenkins-ci.org/browse/JENKINS-47699[JENKINS-47699]:
Allow user-scope credentials to be used as `+input+` step parameters.
* Internal: Replace uses of deprecated APIs
(https://github.com/jenkinsci/pipeline-input-step-plugin/pull/37[PR 37])

[[PipelineInputStepPlugin-2.10(Mar18,2019)]]
=== 2.10 (Mar 18, 2019)

* Trim submitter names before making comparisons to avoid issues with
whitespace
(https://github.com/jenkinsci/pipeline-input-step-plugin/pull/30[PR 30])
* Add internationalization support
(https://github.com/jenkinsci/pipeline-input-step-plugin/pull/23[PR 23])
* Internal: Update dependencies and fix resulting test failures so that
the plugin's tests pass successfully when run using the PCT
(https://github.com/jenkinsci/pipeline-input-step-plugin/pull/31[PR 31])

[[PipelineInputStepPlugin-2.9(Dec14,2018)]]
=== 2.9 (Dec 14, 2018)

* https://issues.jenkins-ci.org/browse/JENKINS-55181[JENKINS-55181]
Compare the ID of the user attempting to submit an input step against
the list of valid submitters using the IdStrategy and GroupIdStrategy
configured by the current security realm. Previously, these comparisons
were always case-sensitive.

[[PipelineInputStepPlugin-2.8(Aug7,2017)]]
=== 2.8 (Aug 7, 2017)

* https://jenkins.io/security/advisory/2017-08-07/[Fix security issue]

[[PipelineInputStepPlugin-2.7(Apr26,2017)]]
=== 2.7 (Apr 26, 2017)

* https://issues.jenkins-ci.org/browse/JENKINS-43856[JENKINS-43856] `+NoSuchMethodError+`
from Blue Ocean code after the change in 2.6.
* https://issues.jenkins-ci.org/browse/JENKINS-40594[JENKINS-40594] The `+submitterParameter+`
option added in 2.4 did not show the correct kind of hyperlink in the
console unless `+parameters+` was also specified.

[[PipelineInputStepPlugin-2.6(Apr24,2017)]]
=== 2.6 (Apr 24, 2017)

* https://issues.jenkins-ci.org/browse/JENKINS-40926[JENKINS-40926] API
to retrieve parameters of a particular submission. No user-visible
change.

[[PipelineInputStepPlugin-2.5(Nov09,2016)]]
=== 2.5 (Nov 09, 2016)

* 2.4 was corrupt.

[[PipelineInputStepPlugin-2.4(Nov09,2016)]]
=== 2.4 (Nov 09, 2016)

* https://issues.jenkins-ci.org/browse/JENKINS-31425[JENKINS-31425] The
`+submitter+` parameter now accepts a comma-separated list.
* https://issues.jenkins-ci.org/browse/JENKINS-31396[JENKINS-31396]
`+submitterParameter+` parameter added.
* https://issues.jenkins-ci.org/browse/JENKINS-38380[JENKINS-38380]
Interrupting an `+input+` step, for example with `+timeout+`, did not
generally work in a secured system.

[.aui-icon .aui-icon-small .aui-iconfont-error .confluence-information-macro-icon]#
#

Use 2.5 instead.

[[PipelineInputStepPlugin-2.3(Oct21,2016)]]
=== 2.3 (Oct 21, 2016)

* https://issues.jenkins-ci.org/browse/JENKINS-39168[JENKINS-39168]
Exception thrown under some conditions from fix in 2.2.

[[PipelineInputStepPlugin-2.2(Oct20,2016)]]
=== 2.2 (Oct 20, 2016)

* More https://issues.jenkins-ci.org/browse/JENKINS-37154[JENKINS-37154]
tuning timeouts

[[PipelineInputStepPlugin-2.1(Aug08,2016)]]
=== 2.1 (Aug 08, 2016)

* https://issues.jenkins-ci.org/browse/JENKINS-37154[JENKINS-37154]
Deadlock under some conditions when aborting a build waiting in
`+input+`.

[[PipelineInputStepPlugin-2.0(Apr05,2016)]]
=== 2.0 (Apr 05, 2016)

* First release under per-plugin versioning scheme. See
https://github.com/jenkinsci/workflow-plugin/blob/82e7defa37c05c5f004f1ba01c93df61ea7868a5/CHANGES.md[1.x
changelog] for earlier releases.
* Includes the `+input+` step formerly in
https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Supporting+APIs+Plugin[Pipeline
Supporting APIs Plugin].
